import type { Course, Prerequisite, Question, Topic } from "@/lib/types";

export const courses: Course[] = [
  {
    id: "pre-calculo",
    title: "Pre-Calculus",
    shortTitle: "Base",
    description: "Algebra, functions and analytic geometry needed before Calculus.",
    accent: "bg-emerald-500",
  },
  {
    id: "calculo-1",
    title: "Calculo 1",
    shortTitle: "C1",
    description: "Limits, derivatives, derivative applications and first integrals.",
    accent: "bg-sky-500",
  },
  {
    id: "calculo-2",
    title: "Calculo 2",
    shortTitle: "C2",
    description: "Integration techniques, improper integrals, sequences and series.",
    accent: "bg-amber-500",
  },
  {
    id: "calculo-3",
    title: "Calculo 3",
    shortTitle: "C3",
    description: "Vectors, functions of several variables and multiple integrals.",
    accent: "bg-rose-500",
  },
  {
    id: "calculo-4",
    title: "Calculo 4",
    shortTitle: "C4",
    description: "Vector fields, line/surface integrals, vector theorems and ODE basics.",
    accent: "bg-violet-500",
  },
];

export const topics: Topic[] = [
  {
    id: "fatoracao",
    courseId: "pre-calculo",
    title: "Fatoracao",
    description: "Produtos notaveis, fator comum, diferenca de quadrados and trinomials.",
    order: 1,
    outcomes: ["Simplify rational expressions", "Recognize common factor patterns"],
  },
  {
    id: "equacoes",
    courseId: "pre-calculo",
    title: "Equacoes",
    description: "Linear, quadratic and rational equations with domain restrictions.",
    order: 2,
    outcomes: ["Solve equations safely", "Check roots against restrictions"],
  },
  {
    id: "funcoes",
    courseId: "pre-calculo",
    title: "Funcoes",
    description: "Domain, image, composition, inverse functions and graph reading.",
    order: 3,
    outcomes: ["Read function behavior", "Compose and invert simple functions"],
  },
  {
    id: "trigonometria",
    courseId: "pre-calculo",
    title: "Trigonometria",
    description: "Unit circle, identities and transformations used in limits and integrals.",
    order: 4,
    outcomes: ["Use fundamental identities", "Recognize notable angles"],
  },
  {
    id: "log-exp",
    courseId: "pre-calculo",
    title: "Logaritmos e Exponenciais",
    description: "Laws of logarithms, exponential growth and equation solving.",
    order: 5,
    outcomes: ["Manipulate logs", "Solve exponential equations"],
  },
  {
    id: "geometria-analitica",
    courseId: "pre-calculo",
    title: "Geometria Analitica",
    description: "Lines, conics, distance, vectors and coordinate geometry.",
    order: 6,
    outcomes: ["Work with lines and distances", "Translate geometry into equations"],
  },
  {
    id: "limites",
    courseId: "calculo-1",
    title: "Limites",
    description: "Limit laws, one-sided limits, algebraic simplification and notable limits.",
    order: 1,
    outcomes: ["Evaluate indeterminate forms", "Use algebra before applying limit rules"],
  },
  {
    id: "continuidade",
    courseId: "calculo-1",
    title: "Continuidade",
    description: "Continuity by point, interval and removable discontinuities.",
    order: 2,
    outcomes: ["Classify discontinuities", "Apply continuity criteria"],
  },
  {
    id: "derivadas",
    courseId: "calculo-1",
    title: "Derivadas",
    description: "Definition, rules, chain rule, implicit differentiation and interpretation.",
    order: 3,
    outcomes: ["Differentiate composite functions", "Interpret derivative as rate"],
  },
  {
    id: "aplicacoes-derivadas",
    courseId: "calculo-1",
    title: "Aplicacoes de Derivadas",
    description: "Optimization, related rates, monotonicity and concavity.",
    order: 4,
    outcomes: ["Build optimization models", "Use derivative tests"],
  },
  {
    id: "integrais",
    courseId: "calculo-1",
    title: "Integrais",
    description: "Antiderivatives, definite integrals and area interpretation.",
    order: 5,
    outcomes: ["Integrate basic forms", "Apply the Fundamental Theorem"],
  },
  {
    id: "tecnicas-integracao",
    courseId: "calculo-2",
    title: "Tecnicas de Integracao",
    description: "Substitution, integration by parts, partial fractions and trig substitution.",
    order: 1,
    outcomes: ["Choose integration techniques", "Decompose rational functions"],
  },
  {
    id: "integrais-improprias",
    courseId: "calculo-2",
    title: "Integrais Improprias",
    description: "Infinite intervals, vertical asymptotes and convergence tests.",
    order: 2,
    outcomes: ["Convert to limits", "Decide convergence"],
  },
  {
    id: "sequencias-series",
    courseId: "calculo-2",
    title: "Sequencias e Series",
    description: "Convergence, comparison, ratio, root and alternating tests.",
    order: 3,
    outcomes: ["Select a convergence test", "Estimate behavior of terms"],
  },
  {
    id: "series-potencias",
    courseId: "calculo-2",
    title: "Series de Potencias",
    description: "Radius, interval of convergence and Taylor series.",
    order: 4,
    outcomes: ["Find convergence interval", "Build Taylor approximations"],
  },
  {
    id: "vetores",
    courseId: "calculo-3",
    title: "Vetores e Espaco",
    description: "Dot product, cross product, planes and spatial geometry.",
    order: 1,
    outcomes: ["Compute vector products", "Find planes and distances"],
  },
  {
    id: "funcoes-varias",
    courseId: "calculo-3",
    title: "Funcoes de Varias Variaveis",
    description: "Domains, level curves, surfaces and limits in R2/R3.",
    order: 2,
    outcomes: ["Interpret level curves", "Analyze multivariable domains"],
  },
  {
    id: "derivadas-parciais",
    courseId: "calculo-3",
    title: "Derivadas Parciais",
    description: "Partial derivatives, gradient, chain rule and tangent planes.",
    order: 3,
    outcomes: ["Compute gradients", "Approximate with tangent planes"],
  },
  {
    id: "integrais-multiplas",
    courseId: "calculo-3",
    title: "Integrais Multiplas",
    description: "Double and triple integrals, coordinate changes and applications.",
    order: 4,
    outcomes: ["Set up regions", "Change order and coordinates"],
  },
  {
    id: "campos-vetoriais",
    courseId: "calculo-4",
    title: "Campos Vetoriais",
    description: "Vector fields, conservative fields, divergence and curl.",
    order: 1,
    outcomes: ["Classify fields", "Compute divergence and curl"],
  },
  {
    id: "integrais-linha",
    courseId: "calculo-4",
    title: "Integrais de Linha",
    description: "Work, circulation, parametrized curves and path dependence.",
    order: 2,
    outcomes: ["Parametrize curves", "Compute work integrals"],
  },
  {
    id: "superficies",
    courseId: "calculo-4",
    title: "Superficies",
    description: "Parametric surfaces, flux and surface integrals.",
    order: 3,
    outcomes: ["Parametrize surfaces", "Compute flux integrals"],
  },
  {
    id: "teoremas-vetoriais",
    courseId: "calculo-4",
    title: "Teoremas Vetoriais",
    description: "Green, Stokes and Gauss/Divergence theorems.",
    order: 4,
    outcomes: ["Choose a vector theorem", "Convert boundary and region integrals"],
  },
  {
    id: "edos-intro",
    courseId: "calculo-4",
    title: "EDOs Introdutorias",
    description: "First-order separable and linear differential equations.",
    order: 5,
    outcomes: ["Solve separable EDOs", "Use integrating factors"],
  },
];

export const prerequisites: Prerequisite[] = [
  {
    id: "pre-fatoracao",
    title: "Fatoracao",
    description: "Base for limits, rational simplification and partial fractions.",
    examples: ["x^2 - a^2", "common factor", "trinomial factoring"],
    topicIds: ["fatoracao", "limites", "tecnicas-integracao"],
  },
  {
    id: "pre-produtos-notaveis",
    title: "Produtos Notaveis",
    description: "Used to expand, simplify and identify removable discontinuities.",
    examples: ["(a+b)^2", "(a-b)^2", "(a+b)(a-b)"],
    topicIds: ["fatoracao", "limites", "continuidade"],
  },
  {
    id: "pre-equacoes",
    title: "Equacoes",
    description: "Needed for critical points, roots, domains and modeling.",
    examples: ["quadratic roots", "rational equations", "domain restrictions"],
    topicIds: ["equacoes", "aplicacoes-derivadas", "funcoes-varias"],
  },
  {
    id: "pre-funcoes",
    title: "Funcoes",
    description: "Core language for every calculus topic.",
    examples: ["domain", "composition", "inverse"],
    topicIds: ["funcoes", "continuidade", "derivadas", "funcoes-varias"],
  },
  {
    id: "pre-trigonometria",
    title: "Trigonometria",
    description: "Appears in notable limits, substitutions and vector geometry.",
    examples: ["sin^2 x + cos^2 x", "unit circle", "angle addition"],
    topicIds: ["trigonometria", "limites", "tecnicas-integracao", "vetores"],
  },
  {
    id: "pre-log-exp",
    title: "Logaritmos e Exponenciais",
    description: "Needed for growth, derivatives, integrals and series.",
    examples: ["ln(ab)", "e^(a+b)", "log equations"],
    topicIds: ["log-exp", "derivadas", "integrais", "series-potencias"],
  },
  {
    id: "pre-geometria",
    title: "Geometria Analitica",
    description: "Foundation for vectors, curves, planes and integration regions.",
    examples: ["line equation", "distance formula", "planes"],
    topicIds: ["geometria-analitica", "vetores", "integrais-multiplas"],
  },
];

export const seedQuestions: Question[] = [
  {
    id: "q-pre-001",
    courseId: "pre-calculo",
    topicId: "fatoracao",
    prerequisiteIds: ["pre-fatoracao", "pre-produtos-notaveis"],
    prompt: "Qual fatoracao esta correta para x^2 - 9?",
    options: [
      { id: "a", text: "(x - 3)(x + 3)" },
      { id: "b", text: "(x - 9)(x + 1)" },
      { id: "c", text: "(x - 3)^2" },
      { id: "d", text: "x(x - 9)" },
    ],
    correctOptionId: "a",
    explanation: "x^2 - 9 e uma diferenca de quadrados: x^2 - 3^2 = (x - 3)(x + 3).",
    difficulty: "basico",
    errorType: "Confusao em diferenca de quadrados",
    tags: ["fatoracao", "produtos-notaveis"],
  },
  {
    id: "q-pre-002",
    courseId: "pre-calculo",
    topicId: "funcoes",
    prerequisiteIds: ["pre-funcoes"],
    prompt: "Se f(x) = 2x - 1 e g(x) = x^2, qual e (g o f)(3)?",
    options: [
      { id: "a", text: "25" },
      { id: "b", text: "11" },
      { id: "c", text: "5" },
      { id: "d", text: "35" },
    ],
    correctOptionId: "a",
    explanation: "Primeiro f(3) = 5. Depois g(f(3)) = g(5) = 25.",
    difficulty: "basico",
    errorType: "Ordem de composicao de funcoes",
    tags: ["funcoes", "composicao"],
  },
  {
    id: "q-pre-003",
    courseId: "pre-calculo",
    topicId: "trigonometria",
    prerequisiteIds: ["pre-trigonometria"],
    prompt: "Qual identidade permite trocar 1 - cos^2(x) por uma expressao equivalente?",
    options: [
      { id: "a", text: "sin^2(x)" },
      { id: "b", text: "cos^2(x)" },
      { id: "c", text: "tan^2(x)" },
      { id: "d", text: "sec^2(x)" },
    ],
    correctOptionId: "a",
    explanation: "Pela identidade fundamental, sin^2(x) + cos^2(x) = 1, entao 1 - cos^2(x) = sin^2(x).",
    difficulty: "basico",
    errorType: "Identidade trigonometrica fundamental",
    tags: ["trigonometria", "identidades"],
  },
  {
    id: "q-c1-001",
    courseId: "calculo-1",
    topicId: "limites",
    prerequisiteIds: ["pre-fatoracao", "pre-produtos-notaveis"],
    prompt: "Calcule lim_{x -> 2} (x^2 - 4) / (x - 2).",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "2" },
      { id: "c", text: "4" },
      { id: "d", text: "Nao existe" },
    ],
    correctOptionId: "c",
    explanation: "Fatore x^2 - 4 = (x - 2)(x + 2). Para x != 2, sobra x + 2. O limite e 4.",
    difficulty: "basico",
    errorType: "Nao fatorou antes de substituir",
    tags: ["limites", "fatoracao"],
  },
  {
    id: "q-c1-002",
    courseId: "calculo-1",
    topicId: "derivadas",
    prerequisiteIds: ["pre-funcoes", "pre-log-exp"],
    prompt: "Qual e a derivada de f(x) = e^x + ln(x)?",
    options: [
      { id: "a", text: "e^x + 1/x" },
      { id: "b", text: "x e^(x-1) + 1/x" },
      { id: "c", text: "e^x + x" },
      { id: "d", text: "e^x - 1/x" },
    ],
    correctOptionId: "a",
    explanation: "A derivada de e^x e e^x, e a derivada de ln(x) e 1/x para x > 0.",
    difficulty: "basico",
    errorType: "Regra de derivacao de log/exponencial",
    tags: ["derivadas", "log-exp"],
  },
  {
    id: "q-c1-003",
    courseId: "calculo-1",
    topicId: "aplicacoes-derivadas",
    prerequisiteIds: ["pre-equacoes", "pre-funcoes"],
    prompt: "Para f(x) = x^2 - 4x + 1, em qual x ocorre o ponto critico?",
    options: [
      { id: "a", text: "x = -2" },
      { id: "b", text: "x = 0" },
      { id: "c", text: "x = 2" },
      { id: "d", text: "x = 4" },
    ],
    correctOptionId: "c",
    explanation: "f'(x) = 2x - 4. Ponto critico quando f'(x) = 0, logo x = 2.",
    difficulty: "medio",
    errorType: "Erro ao resolver f'(x) = 0",
    tags: ["derivadas", "otimizacao"],
  },
  {
    id: "q-c1-004",
    courseId: "calculo-1",
    topicId: "integrais",
    prerequisiteIds: ["pre-funcoes"],
    prompt: "Qual e uma primitiva de 3x^2?",
    options: [
      { id: "a", text: "x^3 + C" },
      { id: "b", text: "6x + C" },
      { id: "c", text: "x^2 + C" },
      { id: "d", text: "9x^3 + C" },
    ],
    correctOptionId: "a",
    explanation: "Pela regra da potencia, integral de 3x^2 dx = x^3 + C.",
    difficulty: "basico",
    errorType: "Regra da potencia na integracao",
    tags: ["integrais", "primitivas"],
  },
  {
    id: "q-c2-001",
    courseId: "calculo-2",
    topicId: "tecnicas-integracao",
    prerequisiteIds: ["pre-fatoracao", "pre-equacoes"],
    prompt: "Em fracoes parciais, como comecar a decomposicao de 1 / (x^2 - 1)?",
    options: [
      { id: "a", text: "A/(x - 1) + B/(x + 1)" },
      { id: "b", text: "A/(x^2) + B/(-1)" },
      { id: "c", text: "A/(x - 1)^2" },
      { id: "d", text: "A/(x + 1)^2" },
    ],
    correctOptionId: "a",
    explanation: "Fatore x^2 - 1 = (x - 1)(x + 1). Cada fator linear recebe uma parcela.",
    difficulty: "medio",
    errorType: "Fatoracao antes de fracoes parciais",
    tags: ["integracao", "fracoes-parciais"],
  },
  {
    id: "q-c2-002",
    courseId: "calculo-2",
    topicId: "integrais-improprias",
    prerequisiteIds: ["pre-funcoes", "pre-log-exp"],
    prompt: "A integral impropria int_1^infinito 1/x^2 dx e:",
    options: [
      { id: "a", text: "Divergente" },
      { id: "b", text: "Convergente e vale 1" },
      { id: "c", text: "Convergente e vale 2" },
      { id: "d", text: "Nao pode ser escrita como limite" },
    ],
    correctOptionId: "b",
    explanation: "int_1^b x^-2 dx = [-1/x]_1^b = 1 - 1/b. Ao tomar b -> infinito, o valor e 1.",
    difficulty: "medio",
    errorType: "Tratamento de limite no infinito",
    tags: ["integrais-improprias", "convergencia"],
  },
  {
    id: "q-c2-003",
    courseId: "calculo-2",
    topicId: "sequencias-series",
    prerequisiteIds: ["pre-funcoes"],
    prompt: "Se a_n = 1/n, qual e lim_{n -> infinito} a_n?",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "1" },
      { id: "c", text: "infinito" },
      { id: "d", text: "Nao existe" },
    ],
    correctOptionId: "a",
    explanation: "Conforme n cresce, 1/n se aproxima de 0.",
    difficulty: "basico",
    errorType: "Comportamento assintotico de sequencias",
    tags: ["sequencias", "limite"],
  },
  {
    id: "q-c2-004",
    courseId: "calculo-2",
    topicId: "series-potencias",
    prerequisiteIds: ["pre-log-exp", "pre-funcoes"],
    prompt: "A serie de Taylor de e^x em torno de 0 comeca com:",
    options: [
      { id: "a", text: "1 + x + x^2/2! + x^3/3! + ..." },
      { id: "b", text: "x + x^2 + x^3 + ..." },
      { id: "c", text: "1 - x + x^2 - x^3 + ..." },
      { id: "d", text: "ln(x) + x + ..." },
    ],
    correctOptionId: "a",
    explanation: "e^x = sum x^n/n!, entao os primeiros termos sao 1 + x + x^2/2! + x^3/3! + ...",
    difficulty: "medio",
    errorType: "Forma da serie de Taylor de e^x",
    tags: ["series", "taylor"],
  },
  {
    id: "q-c3-001",
    courseId: "calculo-3",
    topicId: "vetores",
    prerequisiteIds: ["pre-geometria"],
    prompt: "O produto escalar de u = (1, 2, 0) e v = (3, -1, 4) e:",
    options: [
      { id: "a", text: "1" },
      { id: "b", text: "5" },
      { id: "c", text: "8" },
      { id: "d", text: "12" },
    ],
    correctOptionId: "a",
    explanation: "u . v = 1*3 + 2*(-1) + 0*4 = 3 - 2 + 0 = 1.",
    difficulty: "basico",
    errorType: "Produto escalar em R3",
    tags: ["vetores", "produto-escalar"],
  },
  {
    id: "q-c3-002",
    courseId: "calculo-3",
    topicId: "derivadas-parciais",
    prerequisiteIds: ["pre-funcoes", "pre-equacoes"],
    prompt: "Para f(x,y) = x^2y + y^3, qual e partial f / partial x?",
    options: [
      { id: "a", text: "2xy" },
      { id: "b", text: "x^2 + 3y^2" },
      { id: "c", text: "2xy + 3y^2" },
      { id: "d", text: "2x + y" },
    ],
    correctOptionId: "a",
    explanation: "Na derivada parcial em x, y e constante. Derive x^2y como 2xy e y^3 como 0.",
    difficulty: "medio",
    errorType: "Confusao entre variavel e constante",
    tags: ["parciais", "gradiente"],
  },
  {
    id: "q-c3-003",
    courseId: "calculo-3",
    topicId: "integrais-multiplas",
    prerequisiteIds: ["pre-geometria", "pre-funcoes"],
    prompt: "A integral dupla de 1 sobre um retangulo R mede:",
    options: [
      { id: "a", text: "A area de R" },
      { id: "b", text: "O perimetro de R" },
      { id: "c", text: "Sempre 0" },
      { id: "d", text: "A diagonal de R" },
    ],
    correctOptionId: "a",
    explanation: "Integrar a funcao constante 1 sobre uma regiao plana retorna a area dessa regiao.",
    difficulty: "basico",
    errorType: "Interpretacao geometrica da integral dupla",
    tags: ["integrais-multiplas", "area"],
  },
  {
    id: "q-c4-001",
    courseId: "calculo-4",
    topicId: "campos-vetoriais",
    prerequisiteIds: ["pre-geometria", "pre-funcoes"],
    prompt: "Para F(x,y) = (P,Q) = (x, y), a divergencia em R2 e:",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "1" },
      { id: "c", text: "2" },
      { id: "d", text: "x + y" },
    ],
    correctOptionId: "c",
    explanation: "div F = partial P/partial x + partial Q/partial y = 1 + 1 = 2.",
    difficulty: "medio",
    errorType: "Definicao de divergencia",
    tags: ["campos-vetoriais", "divergencia"],
  },
  {
    id: "q-c4-002",
    courseId: "calculo-4",
    topicId: "integrais-linha",
    prerequisiteIds: ["pre-geometria", "pre-funcoes"],
    prompt: "Uma curva r(t) = (cos t, sin t), 0 <= t <= 2pi, descreve:",
    options: [
      { id: "a", text: "Um segmento de reta" },
      { id: "b", text: "A circunferencia unitaria completa" },
      { id: "c", text: "Uma parabola" },
      { id: "d", text: "Uma elipse de eixo maior 2" },
    ],
    correctOptionId: "b",
    explanation: "cos^2(t) + sin^2(t) = 1, e o intervalo percorre uma volta completa.",
    difficulty: "basico",
    errorType: "Leitura de parametrizacao",
    tags: ["integrais-linha", "parametrizacao"],
  },
  {
    id: "q-c4-003",
    courseId: "calculo-4",
    topicId: "teoremas-vetoriais",
    prerequisiteIds: ["pre-geometria", "pre-trigonometria"],
    prompt: "O Teorema de Green relaciona uma integral de linha fechada no plano com:",
    options: [
      { id: "a", text: "Uma integral dupla sobre a regiao interna" },
      { id: "b", text: "Uma integral tripla no espaco" },
      { id: "c", text: "Uma serie de potencias" },
      { id: "d", text: "Uma derivada ordinaria" },
    ],
    correctOptionId: "a",
    explanation: "Green converte circulacao na fronteira fechada em integral dupla sobre a regiao plana.",
    difficulty: "avancado",
    errorType: "Escolha do teorema vetorial",
    tags: ["green", "teoremas-vetoriais"],
  },
];

export function getCourse(courseId: string) {
  return courses.find((course) => course.id === courseId);
}

export function getTopic(topicId: string) {
  return topics.find((topic) => topic.id === topicId);
}

export function getPrerequisite(prerequisiteId: string) {
  return prerequisites.find((prerequisite) => prerequisite.id === prerequisiteId);
}

export function getTopicsByCourse(courseId: string) {
  return topics
    .filter((topic) => topic.courseId === courseId)
    .sort((a, b) => a.order - b.order);
}
