import type { Course, Prerequisite, Question, Topic } from "@/lib/types";

export const courses: Course[] = [
  {
    id: "pre-calculo",
    title: "Pré-cálculo",
    shortTitle: "Base",
    description: "Álgebra, funções e geometria analítica necessárias antes de Cálculo.",
    accent: "bg-emerald-500",
  },
  {
    id: "calculo-1",
    title: "Cálculo 1",
    shortTitle: "C1",
    description: "Limites, derivadas, aplicações de derivadas e primeiras integrais.",
    accent: "bg-sky-500",
  },
  {
    id: "calculo-2",
    title: "Cálculo 2",
    shortTitle: "C2",
    description: "Técnicas de integração, integrais impróprias, sequências e séries.",
    accent: "bg-amber-500",
  },
  {
    id: "calculo-3",
    title: "Cálculo 3",
    shortTitle: "C3",
    description: "Vetores, funções de várias variáveis e integrais múltiplas.",
    accent: "bg-rose-500",
  },
  {
    id: "calculo-4",
    title: "Cálculo 4",
    shortTitle: "C4",
    description: "Campos vetoriais, integrais de linha/superfície, teoremas vetoriais e EDOs.",
    accent: "bg-violet-500",
  },
];

export const topics: Topic[] = [
  {
    id: "fatoracao",
    courseId: "pre-calculo",
    title: "Fatoração",
    description: "Produtos notáveis, fator comum, diferença de quadrados e trinômios.",
    order: 1,
    outcomes: ["Simplificar expressões racionais", "Reconhecer padrões de fatoração"],
  },
  {
    id: "equacoes",
    courseId: "pre-calculo",
    title: "Equações",
    description: "Equações lineares, quadráticas e racionais com restrições de domínio.",
    order: 2,
    outcomes: ["Resolver equações com segurança", "Conferir raízes contra restrições"],
  },
  {
    id: "funcoes",
    courseId: "pre-calculo",
    title: "Funções",
    description: "Domínio, imagem, composição, funções inversas e leitura de gráficos.",
    order: 3,
    outcomes: ["Ler comportamento de funções", "Compor e inverter funções simples"],
  },
  {
    id: "trigonometria",
    courseId: "pre-calculo",
    title: "Trigonometria",
    description: "Círculo trigonométrico, identidades e transformações usadas em limites e integrais.",
    order: 4,
    outcomes: ["Usar identidades fundamentais", "Reconhecer arcos notáveis"],
  },
  {
    id: "log-exp",
    courseId: "pre-calculo",
    title: "Logaritmos e Exponenciais",
    description: "Propriedades de logaritmos, crescimento exponencial e resolução de equações.",
    order: 5,
    outcomes: ["Manipular logaritmos", "Resolver equações exponenciais"],
  },
  {
    id: "geometria-analitica",
    courseId: "pre-calculo",
    title: "Geometria Analítica",
    description: "Retas, cônicas, distância, vetores e geometria no plano cartesiano.",
    order: 6,
    outcomes: ["Trabalhar com retas e distâncias", "Traduzir geometria em equações"],
  },
  {
    id: "limites",
    courseId: "calculo-1",
    title: "Limites",
    description: "Leis de limites, limites laterais, simplificação algébrica e limites notáveis.",
    order: 1,
    outcomes: ["Avaliar formas indeterminadas", "Usar álgebra antes das regras de limite"],
  },
  {
    id: "continuidade",
    courseId: "calculo-1",
    title: "Continuidade",
    description: "Continuidade em ponto, em intervalo e descontinuidades removíveis.",
    order: 2,
    outcomes: ["Classificar descontinuidades", "Aplicar critérios de continuidade"],
  },
  {
    id: "derivadas",
    courseId: "calculo-1",
    title: "Derivadas",
    description: "Definição, regras, regra da cadeia, derivação implícita e interpretação.",
    order: 3,
    outcomes: ["Derivar funções compostas", "Interpretar derivada como taxa de variação"],
  },
  {
    id: "aplicacoes-derivadas",
    courseId: "calculo-1",
    title: "Aplicações de Derivadas",
    description: "Otimização, taxas relacionadas, monotonicidade e concavidade.",
    order: 4,
    outcomes: ["Montar modelos de otimização", "Usar testes com derivadas"],
  },
  {
    id: "integrais",
    courseId: "calculo-1",
    title: "Integrais",
    description: "Primitivas, integrais definidas e interpretação como área.",
    order: 5,
    outcomes: ["Integrar formas básicas", "Aplicar o Teorema Fundamental"],
  },
  {
    id: "tecnicas-integracao",
    courseId: "calculo-2",
    title: "Técnicas de Integração",
    description: "Substituição, integração por partes, frações parciais e substituição trigonométrica.",
    order: 1,
    outcomes: ["Escolher técnicas de integração", "Decompor funções racionais"],
  },
  {
    id: "integrais-improprias",
    courseId: "calculo-2",
    title: "Integrais Impróprias",
    description: "Intervalos infinitos, assíntotas verticais e testes de convergência.",
    order: 2,
    outcomes: ["Converter para limites", "Decidir convergência"],
  },
  {
    id: "sequencias-series",
    courseId: "calculo-2",
    title: "Sequências e Séries",
    description: "Convergência, comparação, razão, raiz e séries alternadas.",
    order: 3,
    outcomes: ["Selecionar teste de convergência", "Estimar comportamento dos termos"],
  },
  {
    id: "series-potencias",
    courseId: "calculo-2",
    title: "Séries de Potências",
    description: "Raio, intervalo de convergência e séries de Taylor.",
    order: 4,
    outcomes: ["Encontrar intervalo de convergência", "Construir aproximações de Taylor"],
  },
  {
    id: "vetores",
    courseId: "calculo-3",
    title: "Vetores e Espaço",
    description: "Produto escalar, produto vetorial, planos e geometria espacial.",
    order: 1,
    outcomes: ["Calcular produtos vetoriais", "Encontrar planos e distâncias"],
  },
  {
    id: "funcoes-varias",
    courseId: "calculo-3",
    title: "Funções de Várias Variáveis",
    description: "Domínios, curvas de nível, superfícies e limites em R2/R3.",
    order: 2,
    outcomes: ["Interpretar curvas de nível", "Analisar domínios multivariáveis"],
  },
  {
    id: "derivadas-parciais",
    courseId: "calculo-3",
    title: "Derivadas Parciais",
    description: "Derivadas parciais, gradiente, regra da cadeia e planos tangentes.",
    order: 3,
    outcomes: ["Calcular gradientes", "Aproximar com planos tangentes"],
  },
  {
    id: "integrais-multiplas",
    courseId: "calculo-3",
    title: "Integrais Múltiplas",
    description: "Integrais duplas e triplas, mudanças de coordenadas e aplicações.",
    order: 4,
    outcomes: ["Montar regiões", "Trocar ordem e coordenadas"],
  },
  {
    id: "campos-vetoriais",
    courseId: "calculo-4",
    title: "Campos Vetoriais",
    description: "Campos vetoriais, campos conservativos, divergente e rotacional.",
    order: 1,
    outcomes: ["Classificar campos", "Calcular divergente e rotacional"],
  },
  {
    id: "integrais-linha",
    courseId: "calculo-4",
    title: "Integrais de Linha",
    description: "Trabalho, circulação, curvas parametrizadas e dependência do caminho.",
    order: 2,
    outcomes: ["Parametrizar curvas", "Calcular integrais de trabalho"],
  },
  {
    id: "superficies",
    courseId: "calculo-4",
    title: "Superficies",
    description: "Superfícies paramétricas, fluxo e integrais de superfície.",
    order: 3,
    outcomes: ["Parametrizar superfícies", "Calcular integrais de fluxo"],
  },
  {
    id: "teoremas-vetoriais",
    courseId: "calculo-4",
    title: "Teoremas Vetoriais",
    description: "Teoremas de Green, Stokes e Gauss/Divergência.",
    order: 4,
    outcomes: ["Escolher um teorema vetorial", "Converter integrais de fronteira e região"],
  },
  {
    id: "edos-intro",
    courseId: "calculo-4",
    title: "EDOs Introdutórias",
    description: "Equações diferenciais separáveis e lineares de primeira ordem.",
    order: 5,
    outcomes: ["Resolver EDOs separáveis", "Usar fatores integrantes"],
  },
];

export const prerequisites: Prerequisite[] = [
  {
    id: "pre-fatoracao",
    title: "Fatoração",
    description: "Base para limites, simplificação racional e frações parciais.",
    examples: ["x^2 - a^2", "fator comum", "trinômios"],
    topicIds: ["fatoracao", "limites", "tecnicas-integracao"],
  },
  {
    id: "pre-produtos-notaveis",
    title: "Produtos Notáveis",
    description: "Usados para expandir, simplificar e identificar descontinuidades removíveis.",
    examples: ["(a+b)^2", "(a-b)^2", "(a+b)(a-b)"],
    topicIds: ["fatoracao", "limites", "continuidade"],
  },
  {
    id: "pre-equacoes",
    title: "Equações",
    description: "Necessárias para pontos críticos, raízes, domínios e modelagem.",
    examples: ["raízes quadráticas", "equações racionais", "restrições de domínio"],
    topicIds: ["equacoes", "aplicacoes-derivadas", "funcoes-varias"],
  },
  {
    id: "pre-funcoes",
    title: "Funções",
    description: "Linguagem central para todos os tópicos de cálculo.",
    examples: ["domínio", "composição", "inversa"],
    topicIds: ["funcoes", "continuidade", "derivadas", "funcoes-varias"],
  },
  {
    id: "pre-trigonometria",
    title: "Trigonometria",
    description: "Aparece em limites notáveis, substituições e geometria vetorial.",
    examples: ["sen^2 x + cos^2 x", "círculo trigonométrico", "adição de arcos"],
    topicIds: ["trigonometria", "limites", "tecnicas-integracao", "vetores"],
  },
  {
    id: "pre-log-exp",
    title: "Logaritmos e Exponenciais",
    description: "Necessários para crescimento, derivadas, integrais e séries.",
    examples: ["ln(ab)", "e^(a+b)", "equações logarítmicas"],
    topicIds: ["log-exp", "derivadas", "integrais", "series-potencias"],
  },
  {
    id: "pre-geometria",
    title: "Geometria Analítica",
    description: "Base para vetores, curvas, planos e regiões de integração.",
    examples: ["equação da reta", "fórmula da distância", "planos"],
    topicIds: ["geometria-analitica", "vetores", "integrais-multiplas"],
  },
];

const baseSeedQuestions: Question[] = [
  {
    id: "q-pre-001",
    courseId: "pre-calculo",
    topicId: "fatoracao",
    prerequisiteIds: ["pre-fatoracao", "pre-produtos-notaveis"],
    prompt: "Qual fatoração está correta para x^2 - 9?",
    options: [
      { id: "a", text: "(x - 3)(x + 3)" },
      { id: "b", text: "(x - 9)(x + 1)" },
      { id: "c", text: "(x - 3)^2" },
      { id: "d", text: "x(x - 9)" },
    ],
    correctOptionId: "a",
    explanation: "x^2 - 9 é uma diferença de quadrados: x^2 - 3^2 = (x - 3)(x + 3).",
    difficulty: "basico",
    errorType: "Confusão em diferença de quadrados",
    tags: ["fatoracao", "produtos-notaveis"],
  },
  {
    id: "q-pre-002",
    courseId: "pre-calculo",
    topicId: "funcoes",
    prerequisiteIds: ["pre-funcoes"],
    prompt: "Se f(x) = 2x - 1 e g(x) = x^2, qual é (g o f)(3)?",
    options: [
      { id: "a", text: "25" },
      { id: "b", text: "11" },
      { id: "c", text: "5" },
      { id: "d", text: "35" },
    ],
    correctOptionId: "a",
    explanation: "Primeiro f(3) = 5. Depois g(f(3)) = g(5) = 25.",
    difficulty: "basico",
    errorType: "Ordem de composição de funções",
    tags: ["funcoes", "composicao"],
  },
  {
    id: "q-pre-003",
    courseId: "pre-calculo",
    topicId: "trigonometria",
    prerequisiteIds: ["pre-trigonometria"],
    prompt: "Qual identidade permite trocar 1 - cos^2(x) por uma expressão equivalente?",
    options: [
      { id: "a", text: "sin^2(x)" },
      { id: "b", text: "cos^2(x)" },
      { id: "c", text: "tan^2(x)" },
      { id: "d", text: "sec^2(x)" },
    ],
    correctOptionId: "a",
    explanation: "Pela identidade fundamental, sen^2(x) + cos^2(x) = 1, então 1 - cos^2(x) = sen^2(x).",
    difficulty: "basico",
    errorType: "Identidade trigonométrica fundamental",
    tags: ["trigonometria", "identidades"],
  },
  {
    id: "q-c1-001",
    courseId: "calculo-1",
    topicId: "limites",
    prerequisiteIds: ["pre-fatoracao", "pre-produtos-notaveis"],
    prompt: "Calcule lim_{x -> 2} (x^2 - 4) / (x - 2).",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "2" },
      { id: "c", text: "4" },
      { id: "d", text: "Não existe" },
    ],
    correctOptionId: "c",
    explanation: "Fatore x^2 - 4 = (x - 2)(x + 2). Para x != 2, sobra x + 2. O limite é 4.",
    difficulty: "basico",
    errorType: "Não fatorou antes de substituir",
    tags: ["limites", "fatoracao"],
  },
  {
    id: "q-c1-002",
    courseId: "calculo-1",
    topicId: "derivadas",
    prerequisiteIds: ["pre-funcoes", "pre-log-exp"],
    prompt: "Qual é a derivada de f(x) = e^x + ln(x)?",
    options: [
      { id: "a", text: "e^x + 1/x" },
      { id: "b", text: "x e^(x-1) + 1/x" },
      { id: "c", text: "e^x + x" },
      { id: "d", text: "e^x - 1/x" },
    ],
    correctOptionId: "a",
    explanation: "A derivada de e^x é e^x, e a derivada de ln(x) é 1/x para x > 0.",
    difficulty: "basico",
    errorType: "Regra de derivação de log/exponencial",
    tags: ["derivadas", "log-exp"],
  },
  {
    id: "q-c1-003",
    courseId: "calculo-1",
    topicId: "aplicacoes-derivadas",
    prerequisiteIds: ["pre-equacoes", "pre-funcoes"],
    prompt: "Para f(x) = x^2 - 4x + 1, em qual x ocorre o ponto crítico?",
    options: [
      { id: "a", text: "x = -2" },
      { id: "b", text: "x = 0" },
      { id: "c", text: "x = 2" },
      { id: "d", text: "x = 4" },
    ],
    correctOptionId: "c",
    explanation: "f'(x) = 2x - 4. Ponto crítico quando f'(x) = 0, logo x = 2.",
    difficulty: "medio",
    errorType: "Erro ao resolver f'(x) = 0",
    tags: ["derivadas", "otimizacao"],
  },
  {
    id: "q-c1-004",
    courseId: "calculo-1",
    topicId: "integrais",
    prerequisiteIds: ["pre-funcoes"],
    prompt: "Qual é uma primitiva de 3x^2?",
    options: [
      { id: "a", text: "x^3 + C" },
      { id: "b", text: "6x + C" },
      { id: "c", text: "x^2 + C" },
      { id: "d", text: "9x^3 + C" },
    ],
    correctOptionId: "a",
    explanation: "Pela regra da potência, integral de 3x^2 dx = x^3 + C.",
    difficulty: "basico",
    errorType: "Regra da potência na integração",
    tags: ["integrais", "primitivas"],
  },
  {
    id: "q-c2-001",
    courseId: "calculo-2",
    topicId: "tecnicas-integracao",
    prerequisiteIds: ["pre-fatoracao", "pre-equacoes"],
    prompt: "Em frações parciais, como começar a decomposição de 1 / (x^2 - 1)?",
    options: [
      { id: "a", text: "A/(x - 1) + B/(x + 1)" },
      { id: "b", text: "A/(x^2) + B/(-1)" },
      { id: "c", text: "A/(x - 1)^2" },
      { id: "d", text: "A/(x + 1)^2" },
    ],
    correctOptionId: "a",
    explanation: "Fatore x^2 - 1 = (x - 1)(x + 1). Cada fator linear recebe uma parcela.",
    difficulty: "medio",
    errorType: "Fatoração antes de frações parciais",
    tags: ["integracao", "fracoes-parciais"],
  },
  {
    id: "q-c2-002",
    courseId: "calculo-2",
    topicId: "integrais-improprias",
    prerequisiteIds: ["pre-funcoes", "pre-log-exp"],
    prompt: "A integral imprópria int_1^infinito 1/x^2 dx é:",
    options: [
      { id: "a", text: "Divergente" },
      { id: "b", text: "Convergente e vale 1" },
      { id: "c", text: "Convergente e vale 2" },
      { id: "d", text: "Não pode ser escrita como limite" },
    ],
    correctOptionId: "b",
    explanation: "int_1^b x^-2 dx = [-1/x]_1^b = 1 - 1/b. Ao tomar b -> infinito, o valor é 1.",
    difficulty: "medio",
    errorType: "Tratamento de limite no infinito",
    tags: ["integrais-improprias", "convergencia"],
  },
  {
    id: "q-c2-003",
    courseId: "calculo-2",
    topicId: "sequencias-series",
    prerequisiteIds: ["pre-funcoes"],
    prompt: "Se a_n = 1/n, qual é lim_{n -> infinito} a_n?",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "1" },
      { id: "c", text: "infinito" },
      { id: "d", text: "Não existe" },
    ],
    correctOptionId: "a",
    explanation: "Conforme n cresce, 1/n se aproxima de 0.",
    difficulty: "basico",
    errorType: "Comportamento assintótico de sequências",
    tags: ["sequencias", "limite"],
  },
  {
    id: "q-c2-004",
    courseId: "calculo-2",
    topicId: "series-potencias",
    prerequisiteIds: ["pre-log-exp", "pre-funcoes"],
    prompt: "A série de Taylor de e^x em torno de 0 começa com:",
    options: [
      { id: "a", text: "1 + x + x^2/2! + x^3/3! + ..." },
      { id: "b", text: "x + x^2 + x^3 + ..." },
      { id: "c", text: "1 - x + x^2 - x^3 + ..." },
      { id: "d", text: "ln(x) + x + ..." },
    ],
    correctOptionId: "a",
    explanation: "e^x = soma x^n/n!, então os primeiros termos são 1 + x + x^2/2! + x^3/3! + ...",
    difficulty: "medio",
    errorType: "Forma da série de Taylor de e^x",
    tags: ["series", "taylor"],
  },
  {
    id: "q-c3-001",
    courseId: "calculo-3",
    topicId: "vetores",
    prerequisiteIds: ["pre-geometria"],
    prompt: "O produto escalar de u = (1, 2, 0) e v = (3, -1, 4) é:",
    options: [
      { id: "a", text: "1" },
      { id: "b", text: "5" },
      { id: "c", text: "8" },
      { id: "d", text: "12" },
    ],
    correctOptionId: "a",
    explanation: "u . v = 1*3 + 2*(-1) + 0*4 = 3 - 2 + 0 = 1.",
    difficulty: "basico",
    errorType: "Produto escalar em R3",
    tags: ["vetores", "produto-escalar"],
  },
  {
    id: "q-c3-002",
    courseId: "calculo-3",
    topicId: "derivadas-parciais",
    prerequisiteIds: ["pre-funcoes", "pre-equacoes"],
    prompt: "Para f(x,y) = x^2y + y^3, qual é partial f / partial x?",
    options: [
      { id: "a", text: "2xy" },
      { id: "b", text: "x^2 + 3y^2" },
      { id: "c", text: "2xy + 3y^2" },
      { id: "d", text: "2x + y" },
    ],
    correctOptionId: "a",
    explanation: "Na derivada parcial em x, y é constante. Derive x^2y como 2xy e y^3 como 0.",
    difficulty: "medio",
    errorType: "Confusão entre variável e constante",
    tags: ["parciais", "gradiente"],
  },
  {
    id: "q-c3-003",
    courseId: "calculo-3",
    topicId: "integrais-multiplas",
    prerequisiteIds: ["pre-geometria", "pre-funcoes"],
    prompt: "A integral dupla de 1 sobre um retângulo R mede:",
    options: [
      { id: "a", text: "A área de R" },
      { id: "b", text: "O perímetro de R" },
      { id: "c", text: "Sempre 0" },
      { id: "d", text: "A diagonal de R" },
    ],
    correctOptionId: "a",
    explanation: "Integrar a função constante 1 sobre uma região plana retorna a área dessa região.",
    difficulty: "basico",
    errorType: "Interpretação geométrica da integral dupla",
    tags: ["integrais-multiplas", "area"],
  },
  {
    id: "q-c4-001",
    courseId: "calculo-4",
    topicId: "campos-vetoriais",
    prerequisiteIds: ["pre-geometria", "pre-funcoes"],
    prompt: "Para F(x,y) = (P,Q) = (x, y), a divergência em R2 é:",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "1" },
      { id: "c", text: "2" },
      { id: "d", text: "x + y" },
    ],
    correctOptionId: "c",
    explanation: "div F = partial P/partial x + partial Q/partial y = 1 + 1 = 2.",
    difficulty: "medio",
    errorType: "Definição de divergência",
    tags: ["campos-vetoriais", "divergencia"],
  },
  {
    id: "q-c4-002",
    courseId: "calculo-4",
    topicId: "integrais-linha",
    prerequisiteIds: ["pre-geometria", "pre-funcoes"],
    prompt: "Uma curva r(t) = (cos t, sen t), 0 <= t <= 2pi, descreve:",
    options: [
      { id: "a", text: "Um segmento de reta" },
      { id: "b", text: "A circunferência unitária completa" },
      { id: "c", text: "Uma parábola" },
      { id: "d", text: "Uma elipse de semieixos 2 e 1" },
    ],
    correctOptionId: "b",
    explanation: "cos^2(t) + sen^2(t) = 1, e o intervalo percorre uma volta completa.",
    difficulty: "basico",
    errorType: "Leitura de parametrização",
    tags: ["integrais-linha", "parametrizacao"],
  },
  {
    id: "q-c4-003",
    courseId: "calculo-4",
    topicId: "teoremas-vetoriais",
    prerequisiteIds: ["pre-geometria", "pre-trigonometria"],
    prompt: "O Teorema de Green relaciona uma integral de linha fechada no plano com:",
    options: [
      { id: "a", text: "Uma integral dupla sobre a região interna" },
      { id: "b", text: "Uma integral tripla no espaco" },
      { id: "c", text: "Uma série de potências" },
      { id: "d", text: "Uma derivada ordinária" },
    ],
    correctOptionId: "a",
    explanation: "Green converte circulação na fronteira fechada em integral dupla sobre a região plana.",
    difficulty: "avancado",
    errorType: "Escolha do teorema vetorial",
    tags: ["green", "teoremas-vetoriais"],
  },
];

type ExtraQuestion = {
  id: string;
  courseId: Question["courseId"];
  topicId: string;
  difficulty: Question["difficulty"];
  prompt: string;
  choices: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
  explanation: string;
  prerequisiteIds: string[];
  errorType: string;
  tags: string[];
};

const optionIds = ["a", "b", "c", "d"] as const;

function makeQuestion(input: ExtraQuestion): Question {
  return {
    id: input.id,
    courseId: input.courseId,
    topicId: input.topicId,
    prerequisiteIds: input.prerequisiteIds,
    prompt: input.prompt,
    options: input.choices.map((text, index) => ({
      id: optionIds[index],
      text,
      ...(index === input.correct
        ? {}
        : {
            misconception: input.errorType,
            prerequisiteId: input.prerequisiteIds[0],
          }),
    })),
    correctOptionId: optionIds[input.correct],
    explanation: input.explanation,
    difficulty: input.difficulty,
    errorType: input.errorType,
    tags: input.tags,
  };
}

const supplementalQuestions: Question[] = [
  makeQuestion({ id: "q-pre-fat-02", courseId: "pre-calculo", topicId: "fatoracao", difficulty: "basico", prompt: "Coloque 6x² − 9x em evidência.", choices: ["3x(2x − 3)", "3(2x² − 3x)", "x(6x − 9x)", "3x(2x + 3)"], correct: 0, explanation: "O máximo fator comum é 3x: 6x² − 9x = 3x(2x − 3).", prerequisiteIds: ["pre-fatoracao"], errorType: "Fator comum incompleto", tags: ["fatoracao", "fator-comum"] }),
  makeQuestion({ id: "q-pre-fat-03", courseId: "pre-calculo", topicId: "fatoracao", difficulty: "basico", prompt: "Fatore x² + 5x + 6.", choices: ["(x + 2)(x + 3)", "(x − 2)(x − 3)", "(x + 1)(x + 6)", "(x − 2)(x + 3)"], correct: 0, explanation: "Procuramos dois números de soma 5 e produto 6: 2 e 3.", prerequisiteIds: ["pre-fatoracao"], errorType: "Soma e produto no trinômio", tags: ["fatoracao", "trinomio"] }),
  makeQuestion({ id: "q-pre-fat-04", courseId: "pre-calculo", topicId: "fatoracao", difficulty: "medio", prompt: "Simplifique (x² − 4)/(x² − x − 2), com x ≠ −1 e x ≠ 2.", choices: ["(x + 2)/(x + 1)", "(x − 2)/(x − 1)", "(x + 2)/(x − 1)", "1"], correct: 0, explanation: "Fatore: (x−2)(x+2)/[(x−2)(x+1)]. Cancelando x−2, resulta (x+2)/(x+1).", prerequisiteIds: ["pre-fatoracao"], errorType: "Cancelamento sem fatorar", tags: ["fatoracao", "racional"] }),
  makeQuestion({ id: "q-pre-eq-01", courseId: "pre-calculo", topicId: "equacoes", difficulty: "basico", prompt: "Resolva 2x + 5 = 17.", choices: ["x = 6", "x = 11", "x = 4", "x = −6"], correct: 0, explanation: "Subtraia 5: 2x=12; depois divida por 2: x=6.", prerequisiteIds: ["pre-equacoes"], errorType: "Operação inversa incorreta", tags: ["equacoes", "linear"] }),
  makeQuestion({ id: "q-pre-log-01", courseId: "pre-calculo", topicId: "log-exp", difficulty: "basico", prompt: "Se 2ˣ = 8, qual é x?", choices: ["3", "4", "2", "8"], correct: 0, explanation: "Como 8 = 2³, a igualdade das bases dá x=3.", prerequisiteIds: ["pre-log-exp"], errorType: "Conversão entre forma exponencial e potência", tags: ["exponenciais"] }),
  makeQuestion({ id: "q-pre-geo-01", courseId: "pre-calculo", topicId: "geometria-analitica", difficulty: "basico", prompt: "Qual é a distância entre A=(1,2) e B=(4,6)?", choices: ["5", "7", "√7", "25"], correct: 0, explanation: "d=√[(4−1)²+(6−2)²]=√(9+16)=5.", prerequisiteIds: ["pre-geometria"], errorType: "Fórmula da distância", tags: ["geometria", "distancia"] }),
  makeQuestion({ id: "q-c1-lim-02", courseId: "calculo-1", topicId: "limites", difficulty: "basico", prompt: "Calcule lim x→3 de (2x + 1).", choices: ["7", "6", "3", "Não existe"], correct: 0, explanation: "Funções lineares são contínuas; basta substituir x=3: 2·3+1=7.", prerequisiteIds: ["pre-funcoes"], errorType: "Substituição em função contínua", tags: ["limites", "continuidade"] }),
  makeQuestion({ id: "q-c1-lim-03", courseId: "calculo-1", topicId: "limites", difficulty: "medio", prompt: "Calcule lim x→0 de sen(3x)/x.", choices: ["3", "1", "0", "Não existe"], correct: 0, explanation: "Escreva sen(3x)/x = 3·sen(3x)/(3x); o limite notável vale 1.", prerequisiteIds: ["pre-trigonometria"], errorType: "Escala no limite trigonométrico", tags: ["limites", "trigonometria"] }),
  makeQuestion({ id: "q-c1-lim-04", courseId: "calculo-1", topicId: "limites", difficulty: "medio", prompt: "Qual é lim x→∞ de (5x²−1)/(2x²+3x)?", choices: ["5/2", "2/5", "0", "∞"], correct: 0, explanation: "Numerador e denominador têm o mesmo grau; o limite é a razão 5/2 dos coeficientes líderes.", prerequisiteIds: ["pre-funcoes"], errorType: "Comparação de graus no infinito", tags: ["limites", "infinito"] }),
  makeQuestion({ id: "q-c1-lim-05", courseId: "calculo-1", topicId: "limites", difficulty: "avancado", prompt: "Para f(x,y)=(x²y)/(x⁴+y²), qual é o limite quando (x,y)→(0,0)?", choices: ["Não existe", "0", "1/2", "1"], correct: 0, explanation: "Pelo caminho y=x², f=x⁴/(2x⁴)=1/2; por y=0, f=0. Caminhos diferentes dão valores diferentes.", prerequisiteIds: ["pre-funcoes"], errorType: "Teste insuficiente de caminhos", tags: ["limites", "varias-variaveis"] }),
  makeQuestion({ id: "q-c1-cont-01", courseId: "calculo-1", topicId: "continuidade", difficulty: "medio", prompt: "Defina f(2) para tornar f(x)=(x²−4)/(x−2), x≠2, contínua em x=2.", choices: ["4", "2", "0", "Não é possível"], correct: 0, explanation: "Para x≠2, f(x)=x+2; portanto lim x→2 f(x)=4 e devemos definir f(2)=4.", prerequisiteIds: ["pre-produtos-notaveis"], errorType: "Confusão entre valor e limite", tags: ["continuidade", "removivel"] }),
  makeQuestion({ id: "q-c1-der-02", courseId: "calculo-1", topicId: "derivadas", difficulty: "basico", prompt: "Se s(t)=4t², qual é a velocidade instantânea v(t)?", choices: ["8t", "4t", "8", "2t"], correct: 0, explanation: "Velocidade é a derivada da posição: v(t)=s′(t)=8t.", prerequisiteIds: ["pre-funcoes"], errorType: "Regra da potência", tags: ["derivadas", "cinematica"] }),
  makeQuestion({ id: "q-c1-der-03", courseId: "calculo-1", topicId: "derivadas", difficulty: "medio", prompt: "Derive h(x)=(x²+1)⁵.", choices: ["10x(x²+1)⁴", "5(x²+1)⁴", "10x(x²+1)⁵", "5x(x²+1)⁴"], correct: 0, explanation: "Regra da cadeia: 5(x²+1)⁴ multiplicado pela derivada interna 2x.", prerequisiteIds: ["pre-funcoes"], errorType: "Omissão da derivada interna", tags: ["derivadas", "cadeia"] }),
  makeQuestion({ id: "q-c1-der-04", courseId: "calculo-1", topicId: "derivadas", difficulty: "medio", prompt: "Se xy+y²=6, qual é dy/dx onde x+2y≠0?", choices: ["−y/(x+2y)", "−x/(x+2y)", "y/(x+2y)", "−y/(2x+y)"], correct: 0, explanation: "Derivando: y+x y′+2y y′=0; logo y′=−y/(x+2y).", prerequisiteIds: ["pre-equacoes"], errorType: "Derivação implícita do produto", tags: ["derivadas", "implicita"] }),
  makeQuestion({ id: "q-c1-der-05", courseId: "calculo-1", topicId: "derivadas", difficulty: "avancado", prompt: "Para f(x)=xˣ, x>0, qual é f′(x)?", choices: ["xˣ(ln x+1)", "x·xˣ⁻¹", "xˣ ln x", "xˣ⁻¹"], correct: 0, explanation: "Use logaritmo: ln f=x ln x. Então f′/f=ln x+1 e f′=xˣ(ln x+1).", prerequisiteIds: ["pre-log-exp"], errorType: "Derivação logarítmica", tags: ["derivadas", "logaritmica"] }),
  makeQuestion({ id: "q-c2-tec-02", courseId: "calculo-2", topicId: "tecnicas-integracao", difficulty: "basico", prompt: "Qual substituição simplifica ∫2x cos(x²) dx?", choices: ["u=x²", "u=cos x", "u=2x", "u=x³"], correct: 0, explanation: "Com u=x², du=2x dx e a integral vira ∫cos u du.", prerequisiteIds: ["pre-funcoes"], errorType: "Escolha da substituição", tags: ["integracao", "substituicao"] }),
  makeQuestion({ id: "q-c2-tec-03", courseId: "calculo-2", topicId: "tecnicas-integracao", difficulty: "basico", prompt: "Uma primitiva de 1/(1+x²) é:", choices: ["arctan x + C", "ln(1+x²)+C", "1/(2x)+C", "sen x + C"], correct: 0, explanation: "A derivada de arctan x é 1/(1+x²).", prerequisiteIds: ["pre-funcoes"], errorType: "Primitiva trigonométrica inversa", tags: ["integracao", "primitivas"] }),
  makeQuestion({ id: "q-c2-tec-04", courseId: "calculo-2", topicId: "tecnicas-integracao", difficulty: "medio", prompt: "Na integração por partes de ∫x eˣ dx, uma escolha eficiente é:", choices: ["u=x e dv=eˣdx", "u=eˣ e dv=x dx", "u=xeˣ e dv=dx", "u=1 e dv=xeˣdx"], correct: 0, explanation: "Escolher u=x reduz o polinômio ao derivar, e integrar dv=eˣdx é imediato.", prerequisiteIds: ["pre-log-exp"], errorType: "Escolha de u e dv", tags: ["integracao", "partes"] }),
  makeQuestion({ id: "q-c2-tec-05", courseId: "calculo-2", topicId: "tecnicas-integracao", difficulty: "medio", prompt: "Calcule ∫₀¹ 3x² dx.", choices: ["1", "3", "1/3", "0"], correct: 0, explanation: "Uma primitiva é x³; avaliando de 0 a 1, obtemos 1.", prerequisiteIds: ["pre-funcoes"], errorType: "Avaliação nos limites", tags: ["integracao", "definida"] }),
  makeQuestion({ id: "q-c2-tec-06", courseId: "calculo-2", topicId: "tecnicas-integracao", difficulty: "avancado", prompt: "Para ∫√(9−x²) dx, qual substituição trigonométrica é natural?", choices: ["x=3 sen θ", "x=3 tan θ", "x=3 sec θ", "x=9 sen θ"], correct: 0, explanation: "x=3 sen θ transforma √(9−x²) em 3 cos θ no intervalo apropriado.", prerequisiteIds: ["pre-trigonometria"], errorType: "Substituição trigonométrica inadequada", tags: ["integracao", "substituicao-trigonometrica"] }),
  makeQuestion({ id: "q-c3-var-01", courseId: "calculo-3", topicId: "funcoes-varias", difficulty: "basico", prompt: "O domínio real de f(x,y)=√(4−x²−y²) é:", choices: ["x²+y²≤4", "x²+y²≥4", "x+y≤4", "todo ℝ²"], correct: 0, explanation: "O radicando deve ser não negativo: 4−x²−y²≥0.", prerequisiteIds: ["pre-equacoes"], errorType: "Restrição de domínio multivariável", tags: ["varias-variaveis", "dominio"] }),
  makeQuestion({ id: "q-c3-par-02", courseId: "calculo-3", topicId: "derivadas-parciais", difficulty: "basico", prompt: "Para f(x,y)=3x+2y, qual é ∇f?", choices: ["(3,2)", "(3x,2y)", "(2,3)", "5"], correct: 0, explanation: "∂f/∂x=3 e ∂f/∂y=2; portanto ∇f=(3,2).", prerequisiteIds: ["pre-funcoes"], errorType: "Componentes do gradiente", tags: ["gradiente"] }),
  makeQuestion({ id: "q-c3-par-03", courseId: "calculo-3", topicId: "derivadas-parciais", difficulty: "basico", prompt: "Para z=x²+y², qual é o plano tangente em (1,1,2)?", choices: ["z=2x+2y−2", "z=x+y", "z=2x+2y", "z=x²+y²"], correct: 0, explanation: "z−2=2(x−1)+2(y−1), logo z=2x+2y−2.", prerequisiteIds: ["pre-geometria"], errorType: "Linearização no ponto", tags: ["parciais", "plano-tangente"] }),
  makeQuestion({ id: "q-c3-par-04", courseId: "calculo-3", topicId: "derivadas-parciais", difficulty: "medio", prompt: "Se T(x,y)=x²−y, qual é a taxa direcional em (1,0) na direção unitária (0,1)?", choices: ["−1", "2", "1", "0"], correct: 0, explanation: "∇T=(2x,−1); em (1,0), (2,−1)·(0,1)=−1.", prerequisiteIds: ["pre-geometria"], errorType: "Produto escalar na derivada direcional", tags: ["parciais", "direcional"] }),
  makeQuestion({ id: "q-c3-par-05", courseId: "calculo-3", topicId: "derivadas-parciais", difficulty: "avancado", prompt: "Se z=f(x,y), x=t² e y=eᵗ, então dz/dt é:", choices: ["2t fₓ + eᵗ fᵧ", "fₓ+fᵧ", "t² fₓ+eᵗ fᵧ", "2t+eᵗ"], correct: 0, explanation: "Pela regra da cadeia, dz/dt=fₓ dx/dt+fᵧ dy/dt=2t fₓ+eᵗ fᵧ.", prerequisiteIds: ["pre-funcoes"], errorType: "Regra da cadeia multivariável", tags: ["parciais", "cadeia"] }),
  makeQuestion({ id: "q-c3-par-06", courseId: "calculo-3", topicId: "derivadas-parciais", difficulty: "avancado", prompt: "Para f(x,y)=x²+y², o ponto (0,0) é:", choices: ["mínimo global", "máximo global", "ponto de sela", "não crítico"], correct: 0, explanation: "∇f(0,0)=0 e a Hessiana diag(2,2) é positiva definida; além disso f≥0.", prerequisiteIds: ["pre-equacoes"], errorType: "Classificação pela Hessiana", tags: ["parciais", "hessiana"] }),
  makeQuestion({ id: "q-c4-cam-02", courseId: "calculo-4", topicId: "campos-vetoriais", difficulty: "basico", prompt: "O campo F(x,y)=(−y,x) é visualmente associado a:", choices: ["rotação em torno da origem", "fluxo radial para fora", "campo constante", "fluxo apenas horizontal"], correct: 0, explanation: "F é perpendicular ao vetor posição (x,y), produzindo circulação anti-horária.", prerequisiteIds: ["pre-geometria"], errorType: "Interpretação geométrica do campo", tags: ["campos", "rotacao"] }),
  makeQuestion({ id: "q-c4-cam-03", courseId: "calculo-4", topicId: "campos-vetoriais", difficulty: "basico", prompt: "Para φ(x,y)=x²+y², qual campo é ∇φ?", choices: ["(2x,2y)", "(x,y)", "(2,2)", "(−2y,2x)"], correct: 0, explanation: "O gradiente reúne as derivadas parciais: ∇φ=(2x,2y).", prerequisiteIds: ["pre-funcoes"], errorType: "Cálculo do campo gradiente", tags: ["campos", "gradiente"] }),
  makeQuestion({ id: "q-c4-cam-04", courseId: "calculo-4", topicId: "campos-vetoriais", difficulty: "medio", prompt: "Em uma região simplesmente conexa, se ∂Q/∂x=∂P/∂y para F=(P,Q) de classe C¹, então F é:", choices: ["conservativo", "necessariamente divergente", "constante", "descontínuo"], correct: 0, explanation: "A igualdade das derivadas cruzadas em região simplesmente conexa garante potencial escalar.", prerequisiteIds: ["pre-funcoes"], errorType: "Critério de conservatividade", tags: ["campos", "conservativo"] }),
  makeQuestion({ id: "q-c4-cam-05", courseId: "calculo-4", topicId: "campos-vetoriais", difficulty: "avancado", prompt: "Qual é o rotacional de F(x,y,z)=(yz,xz,xy)?", choices: ["(0,0,0)", "(x,y,z)", "(y,z,x)", "(z,x,y)"], correct: 0, explanation: "As derivadas cruzadas correspondentes são iguais; F=∇(xyz), logo seu rotacional é zero.", prerequisiteIds: ["pre-funcoes"], errorType: "Ordem das componentes do rotacional", tags: ["campos", "rotacional"] }),
  makeQuestion({ id: "q-c4-cam-06", courseId: "calculo-4", topicId: "campos-vetoriais", difficulty: "avancado", prompt: "Para F=(x/r³,y/r³,z/r³), r=√(x²+y²+z²), qual é div F onde r≠0?", choices: ["0", "1/r²", "3/r³", "−1/r³"], correct: 0, explanation: "F é o campo radial inverso ao quadrado; calculando as três derivadas, os termos somam zero fora da origem.", prerequisiteIds: ["pre-funcoes"], errorType: "Divergência de campo radial", tags: ["campos", "divergencia"] }),
  makeQuestion({ id: "q-c4-sup-01", courseId: "calculo-4", topicId: "superficies", difficulty: "medio", prompt: "A parametrização r(u,v)=(u,v,u²+v²) descreve:", choices: ["um paraboloide", "um plano", "uma esfera", "um cilindro"], correct: 0, explanation: "Como x=u, y=v e z=u²+v²=x²+y², trata-se de um paraboloide.", prerequisiteIds: ["pre-geometria"], errorType: "Leitura de superfície parametrizada", tags: ["superficies", "parametrizacao"] }),
  makeQuestion({ id: "q-c4-edo-01", courseId: "calculo-4", topicId: "edos-intro", difficulty: "basico", prompt: "A solução geral de y′=3y é:", choices: ["y=Ce³ᵗ", "y=3t+C", "y=Ceᵗ/3", "y=3eᵗ+C"], correct: 0, explanation: "Separando dy/y=3dt e integrando, ln|y|=3t+C; portanto y=Ce³ᵗ.", prerequisiteIds: ["pre-log-exp"], errorType: "Solução exponencial de EDO separável", tags: ["edo", "separavel"] }),
];

export const seedQuestions: Question[] = [
  ...baseSeedQuestions,
  ...supplementalQuestions,
];

export function getCourse(courseId: string) {
  return courses.find((course) => course.id === courseId);
}

export function getTopic(topicId: string) {
  return topics.find((topic) => topic.id === topicId);
}

export function getPrerequisite(prerequisiteId: string) {
  return prerequisites.find((prerequisite) => prerequisite.id === prerequisiteId);
}

export function getTopicsByCourse(courseId: string) {
  return topics
    .filter((topic) => topic.courseId === courseId)
    .sort((a, b) => a.order - b.order);
}
