import type { Course, Prerequisite, Question, Topic } from "@/lib/types";

export const courses: Course[] = [
  {
    id: "pre-calculo",
    title: "Pré-cálculo",
    shortTitle: "Base",
    description: "Álgebra, funções e geometria analítica necessárias antes de Cálculo.",
    accent: "bg-emerald-500",
  },
  {
    id: "calculo-1",
    title: "Cálculo 1",
    shortTitle: "C1",
    description: "Limites, derivadas, aplicações de derivadas e primeiras integrais.",
    accent: "bg-sky-500",
  },
  {
    id: "calculo-2",
    title: "Cálculo 2",
    shortTitle: "C2",
    description: "Técnicas de integração, integrais impróprias, sequências e séries.",
    accent: "bg-amber-500",
  },
  {
    id: "calculo-3",
    title: "Cálculo 3",
    shortTitle: "C3",
    description: "Vetores, funções de várias variáveis e integrais múltiplas.",
    accent: "bg-rose-500",
  },
  {
    id: "calculo-4",
    title: "Cálculo 4",
    shortTitle: "C4",
    description: "Campos vetoriais, integrais de linha/superfície, teoremas vetoriais e EDOs.",
    accent: "bg-violet-500",
  },
];

export const topics: Topic[] = [
  {
    id: "fatoracao",
    courseId: "pre-calculo",
    title: "Fatoração",
    description: "Produtos notáveis, fator comum, diferença de quadrados e trinômios.",
    order: 1,
    outcomes: ["Simplificar expressões racionais", "Reconhecer padrões de fatoração"],
  },
  {
    id: "equacoes",
    courseId: "pre-calculo",
    title: "Equações",
    description: "Equações lineares, quadráticas e racionais com restrições de domínio.",
    order: 2,
    outcomes: ["Resolver equações com segurança", "Conferir raízes contra restrições"],
  },
  {
    id: "funcoes",
    courseId: "pre-calculo",
    title: "Funções",
    description: "Domínio, imagem, composição, funções inversas e leitura de gráficos.",
    order: 3,
    outcomes: ["Ler comportamento de funções", "Compor e inverter funções simples"],
  },
  {
    id: "trigonometria",
    courseId: "pre-calculo",
    title: "Trigonometria",
    description: "Círculo trigonométrico, identidades e transformações usadas em limites e integrais.",
    order: 4,
    outcomes: ["Usar identidades fundamentais", "Reconhecer arcos notáveis"],
  },
  {
    id: "log-exp",
    courseId: "pre-calculo",
    title: "Logaritmos e Exponenciais",
    description: "Propriedades de logaritmos, crescimento exponencial e resolução de equações.",
    order: 5,
    outcomes: ["Manipular logaritmos", "Resolver equações exponenciais"],
  },
  {
    id: "geometria-analitica",
    courseId: "pre-calculo",
    title: "Geometria Analítica",
    description: "Retas, cônicas, distância, vetores e geometria no plano cartesiano.",
    order: 6,
    outcomes: ["Trabalhar com retas e distâncias", "Traduzir geometria em equações"],
  },
  {
    id: "limites",
    courseId: "calculo-1",
    title: "Limites",
    description: "Leis de limites, limites laterais, simplificação algébrica e limites notáveis.",
    order: 1,
    outcomes: ["Avaliar formas indeterminadas", "Usar álgebra antes das regras de limite"],
  },
  {
    id: "continuidade",
    courseId: "calculo-1",
    title: "Continuidade",
    description: "Continuidade em ponto, em intervalo e descontinuidades removíveis.",
    order: 2,
    outcomes: ["Classificar descontinuidades", "Aplicar critérios de continuidade"],
  },
  {
    id: "derivadas",
    courseId: "calculo-1",
    title: "Derivadas",
    description: "Definição, regras, regra da cadeia, derivação implícita e interpretação.",
    order: 3,
    outcomes: ["Derivar funções compostas", "Interpretar derivada como taxa de variação"],
  },
  {
    id: "aplicacoes-derivadas",
    courseId: "calculo-1",
    title: "Aplicações de Derivadas",
    description: "Otimização, taxas relacionadas, monotonicidade e concavidade.",
    order: 4,
    outcomes: ["Montar modelos de otimização", "Usar testes com derivadas"],
  },
  {
    id: "integrais",
    courseId: "calculo-1",
    title: "Integrais",
    description: "Primitivas, integrais definidas e interpretação como área.",
    order: 5,
    outcomes: ["Integrar formas básicas", "Aplicar o Teorema Fundamental"],
  },
  {
    id: "tecnicas-integracao",
    courseId: "calculo-2",
    title: "Técnicas de Integração",
    description: "Substituição, integração por partes, frações parciais e substituição trigonométrica.",
    order: 1,
    outcomes: ["Escolher técnicas de integração", "Decompor funções racionais"],
  },
  {
    id: "integrais-improprias",
    courseId: "calculo-2",
    title: "Integrais Impróprias",
    description: "Intervalos infinitos, assíntotas verticais e testes de convergência.",
    order: 2,
    outcomes: ["Converter para limites", "Decidir convergência"],
  },
  {
    id: "sequencias-series",
    courseId: "calculo-2",
    title: "Sequências e Séries",
    description: "Convergência, comparação, razão, raiz e séries alternadas.",
    order: 3,
    outcomes: ["Selecionar teste de convergência", "Estimar comportamento dos termos"],
  },
  {
    id: "series-potencias",
    courseId: "calculo-2",
    title: "Séries de Potências",
    description: "Raio, intervalo de convergência e séries de Taylor.",
    order: 4,
    outcomes: ["Encontrar intervalo de convergência", "Construir aproximações de Taylor"],
  },
  {
    id: "vetores",
    courseId: "calculo-3",
    title: "Vetores e Espaço",
    description: "Produto escalar, produto vetorial, planos e geometria espacial.",
    order: 1,
    outcomes: ["Calcular produtos vetoriais", "Encontrar planos e distâncias"],
  },
  {
    id: "funcoes-varias",
    courseId: "calculo-3",
    title: "Funções de Várias Variáveis",
    description: "Domínios, curvas de nível, superfícies e limites em R2/R3.",
    order: 2,
    outcomes: ["Interpretar curvas de nível", "Analisar domínios multivariáveis"],
  },
  {
    id: "derivadas-parciais",
    courseId: "calculo-3",
    title: "Derivadas Parciais",
    description: "Derivadas parciais, gradiente, regra da cadeia e planos tangentes.",
    order: 3,
    outcomes: ["Calcular gradientes", "Aproximar com planos tangentes"],
  },
  {
    id: "integrais-multiplas",
    courseId: "calculo-3",
    title: "Integrais Múltiplas",
    description: "Integrais duplas e triplas, mudanças de coordenadas e aplicações.",
    order: 4,
    outcomes: ["Montar regiões", "Trocar ordem e coordenadas"],
  },
  {
    id: "campos-vetoriais",
    courseId: "calculo-4",
    title: "Campos Vetoriais",
    description: "Campos vetoriais, campos conservativos, divergente e rotacional.",
    order: 1,
    outcomes: ["Classificar campos", "Calcular divergente e rotacional"],
  },
  {
    id: "integrais-linha",
    courseId: "calculo-4",
    title: "Integrais de Linha",
    description: "Trabalho, circulação, curvas parametrizadas e dependência do caminho.",
    order: 2,
    outcomes: ["Parametrizar curvas", "Calcular integrais de trabalho"],
  },
  {
    id: "superficies",
    courseId: "calculo-4",
    title: "Superficies",
    description: "Superfícies paramétricas, fluxo e integrais de superfície.",
    order: 3,
    outcomes: ["Parametrizar superfícies", "Calcular integrais de fluxo"],
  },
  {
    id: "teoremas-vetoriais",
    courseId: "calculo-4",
    title: "Teoremas Vetoriais",
    description: "Teoremas de Green, Stokes e Gauss/Divergência.",
    order: 4,
    outcomes: ["Escolher um teorema vetorial", "Converter integrais de fronteira e região"],
  },
  {
    id: "edos-intro",
    courseId: "calculo-4",
    title: "EDOs Introdutórias",
    description: "Equações diferenciais separáveis e lineares de primeira ordem.",
    order: 5,
    outcomes: ["Resolver EDOs separáveis", "Usar fatores integrantes"],
  },
];

export const prerequisites: Prerequisite[] = [
  {
    id: "pre-fatoracao",
    title: "Fatoração",
    description: "Base para limites, simplificação racional e frações parciais.",
    examples: ["x^2 - a^2", "fator comum", "trinômios"],
    topicIds: ["fatoracao", "limites", "tecnicas-integracao"],
  },
  {
    id: "pre-produtos-notaveis",
    title: "Produtos Notáveis",
    description: "Usados para expandir, simplificar e identificar descontinuidades removíveis.",
    examples: ["(a+b)^2", "(a-b)^2", "(a+b)(a-b)"],
    topicIds: ["fatoracao", "limites", "continuidade"],
  },
  {
    id: "pre-equacoes",
    title: "Equações",
    description: "Necessárias para pontos críticos, raízes, domínios e modelagem.",
    examples: ["raízes quadráticas", "equações racionais", "restrições de domínio"],
    topicIds: ["equacoes", "aplicacoes-derivadas", "funcoes-varias"],
  },
  {
    id: "pre-funcoes",
    title: "Funções",
    description: "Linguagem central para todos os tópicos de cálculo.",
    examples: ["domínio", "composição", "inversa"],
    topicIds: ["funcoes", "continuidade", "derivadas", "funcoes-varias"],
  },
  {
    id: "pre-trigonometria",
    title: "Trigonometria",
    description: "Aparece em limites notáveis, substituições e geometria vetorial.",
    examples: ["sen^2 x + cos^2 x", "círculo trigonométrico", "adição de arcos"],
    topicIds: ["trigonometria", "limites", "tecnicas-integracao", "vetores"],
  },
  {
    id: "pre-log-exp",
    title: "Logaritmos e Exponenciais",
    description: "Necessários para crescimento, derivadas, integrais e séries.",
    examples: ["ln(ab)", "e^(a+b)", "equações logarítmicas"],
    topicIds: ["log-exp", "derivadas", "integrais", "series-potencias"],
  },
  {
    id: "pre-geometria",
    title: "Geometria Analítica",
    description: "Base para vetores, curvas, planos e regiões de integração.",
    examples: ["equação da reta", "fórmula da distância", "planos"],
    topicIds: ["geometria-analitica", "vetores", "integrais-multiplas"],
  },
];

export const seedQuestions: Question[] = [
  {
    id: "q-pre-001",
    courseId: "pre-calculo",
    topicId: "fatoracao",
    prerequisiteIds: ["pre-fatoracao", "pre-produtos-notaveis"],
    prompt: "Qual fatoração está correta para x^2 - 9?",
    options: [
      { id: "a", text: "(x - 3)(x + 3)" },
      { id: "b", text: "(x - 9)(x + 1)" },
      { id: "c", text: "(x - 3)^2" },
      { id: "d", text: "x(x - 9)" },
    ],
    correctOptionId: "a",
    explanation: "x^2 - 9 é uma diferença de quadrados: x^2 - 3^2 = (x - 3)(x + 3).",
    difficulty: "basico",
    errorType: "Confusão em diferença de quadrados",
    tags: ["fatoracao", "produtos-notaveis"],
  },
  {
    id: "q-pre-002",
    courseId: "pre-calculo",
    topicId: "funcoes",
    prerequisiteIds: ["pre-funcoes"],
    prompt: "Se f(x) = 2x - 1 e g(x) = x^2, qual é (g o f)(3)?",
    options: [
      { id: "a", text: "25" },
      { id: "b", text: "11" },
      { id: "c", text: "5" },
      { id: "d", text: "35" },
    ],
    correctOptionId: "a",
    explanation: "Primeiro f(3) = 5. Depois g(f(3)) = g(5) = 25.",
    difficulty: "basico",
    errorType: "Ordem de composição de funções",
    tags: ["funcoes", "composicao"],
  },
  {
    id: "q-pre-003",
    courseId: "pre-calculo",
    topicId: "trigonometria",
    prerequisiteIds: ["pre-trigonometria"],
    prompt: "Qual identidade permite trocar 1 - cos^2(x) por uma expressão equivalente?",
    options: [
      { id: "a", text: "sin^2(x)" },
      { id: "b", text: "cos^2(x)" },
      { id: "c", text: "tan^2(x)" },
      { id: "d", text: "sec^2(x)" },
    ],
    correctOptionId: "a",
    explanation: "Pela identidade fundamental, sen^2(x) + cos^2(x) = 1, então 1 - cos^2(x) = sen^2(x).",
    difficulty: "basico",
    errorType: "Identidade trigonométrica fundamental",
    tags: ["trigonometria", "identidades"],
  },
  {
    id: "q-c1-001",
    courseId: "calculo-1",
    topicId: "limites",
    prerequisiteIds: ["pre-fatoracao", "pre-produtos-notaveis"],
    prompt: "Calcule lim_{x -> 2} (x^2 - 4) / (x - 2).",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "2" },
      { id: "c", text: "4" },
      { id: "d", text: "Não existe" },
    ],
    correctOptionId: "c",
    explanation: "Fatore x^2 - 4 = (x - 2)(x + 2). Para x != 2, sobra x + 2. O limite é 4.",
    difficulty: "basico",
    errorType: "Não fatorou antes de substituir",
    tags: ["limites", "fatoracao"],
  },
  {
    id: "q-c1-002",
    courseId: "calculo-1",
    topicId: "derivadas",
    prerequisiteIds: ["pre-funcoes", "pre-log-exp"],
    prompt: "Qual é a derivada de f(x) = e^x + ln(x)?",
    options: [
      { id: "a", text: "e^x + 1/x" },
      { id: "b", text: "x e^(x-1) + 1/x" },
      { id: "c", text: "e^x + x" },
      { id: "d", text: "e^x - 1/x" },
    ],
    correctOptionId: "a",
    explanation: "A derivada de e^x é e^x, e a derivada de ln(x) é 1/x para x > 0.",
    difficulty: "basico",
    errorType: "Regra de derivação de log/exponencial",
    tags: ["derivadas", "log-exp"],
  },
  {
    id: "q-c1-003",
    courseId: "calculo-1",
    topicId: "aplicacoes-derivadas",
    prerequisiteIds: ["pre-equacoes", "pre-funcoes"],
    prompt: "Para f(x) = x^2 - 4x + 1, em qual x ocorre o ponto crítico?",
    options: [
      { id: "a", text: "x = -2" },
      { id: "b", text: "x = 0" },
      { id: "c", text: "x = 2" },
      { id: "d", text: "x = 4" },
    ],
    correctOptionId: "c",
    explanation: "f'(x) = 2x - 4. Ponto crítico quando f'(x) = 0, logo x = 2.",
    difficulty: "medio",
    errorType: "Erro ao resolver f'(x) = 0",
    tags: ["derivadas", "otimizacao"],
  },
  {
    id: "q-c1-004",
    courseId: "calculo-1",
    topicId: "integrais",
    prerequisiteIds: ["pre-funcoes"],
    prompt: "Qual é uma primitiva de 3x^2?",
    options: [
      { id: "a", text: "x^3 + C" },
      { id: "b", text: "6x + C" },
      { id: "c", text: "x^2 + C" },
      { id: "d", text: "9x^3 + C" },
    ],
    correctOptionId: "a",
    explanation: "Pela regra da potência, integral de 3x^2 dx = x^3 + C.",
    difficulty: "basico",
    errorType: "Regra da potência na integração",
    tags: ["integrais", "primitivas"],
  },
  {
    id: "q-c2-001",
    courseId: "calculo-2",
    topicId: "tecnicas-integracao",
    prerequisiteIds: ["pre-fatoracao", "pre-equacoes"],
    prompt: "Em frações parciais, como começar a decomposição de 1 / (x^2 - 1)?",
    options: [
      { id: "a", text: "A/(x - 1) + B/(x + 1)" },
      { id: "b", text: "A/(x^2) + B/(-1)" },
      { id: "c", text: "A/(x - 1)^2" },
      { id: "d", text: "A/(x + 1)^2" },
    ],
    correctOptionId: "a",
    explanation: "Fatore x^2 - 1 = (x - 1)(x + 1). Cada fator linear recebe uma parcela.",
    difficulty: "medio",
    errorType: "Fatoração antes de frações parciais",
    tags: ["integracao", "fracoes-parciais"],
  },
  {
    id: "q-c2-002",
    courseId: "calculo-2",
    topicId: "integrais-improprias",
    prerequisiteIds: ["pre-funcoes", "pre-log-exp"],
    prompt: "A integral imprópria int_1^infinito 1/x^2 dx é:",
    options: [
      { id: "a", text: "Divergente" },
      { id: "b", text: "Convergente e vale 1" },
      { id: "c", text: "Convergente e vale 2" },
      { id: "d", text: "Não pode ser escrita como limite" },
    ],
    correctOptionId: "b",
    explanation: "int_1^b x^-2 dx = [-1/x]_1^b = 1 - 1/b. Ao tomar b -> infinito, o valor é 1.",
    difficulty: "medio",
    errorType: "Tratamento de limite no infinito",
    tags: ["integrais-improprias", "convergencia"],
  },
  {
    id: "q-c2-003",
    courseId: "calculo-2",
    topicId: "sequencias-series",
    prerequisiteIds: ["pre-funcoes"],
    prompt: "Se a_n = 1/n, qual é lim_{n -> infinito} a_n?",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "1" },
      { id: "c", text: "infinito" },
      { id: "d", text: "Não existe" },
    ],
    correctOptionId: "a",
    explanation: "Conforme n cresce, 1/n se aproxima de 0.",
    difficulty: "basico",
    errorType: "Comportamento assintótico de sequências",
    tags: ["sequencias", "limite"],
  },
  {
    id: "q-c2-004",
    courseId: "calculo-2",
    topicId: "series-potencias",
    prerequisiteIds: ["pre-log-exp", "pre-funcoes"],
    prompt: "A série de Taylor de e^x em torno de 0 começa com:",
    options: [
      { id: "a", text: "1 + x + x^2/2! + x^3/3! + ..." },
      { id: "b", text: "x + x^2 + x^3 + ..." },
      { id: "c", text: "1 - x + x^2 - x^3 + ..." },
      { id: "d", text: "ln(x) + x + ..." },
    ],
    correctOptionId: "a",
    explanation: "e^x = soma x^n/n!, então os primeiros termos são 1 + x + x^2/2! + x^3/3! + ...",
    difficulty: "medio",
    errorType: "Forma da série de Taylor de e^x",
    tags: ["series", "taylor"],
  },
  {
    id: "q-c3-001",
    courseId: "calculo-3",
    topicId: "vetores",
    prerequisiteIds: ["pre-geometria"],
    prompt: "O produto escalar de u = (1, 2, 0) e v = (3, -1, 4) é:",
    options: [
      { id: "a", text: "1" },
      { id: "b", text: "5" },
      { id: "c", text: "8" },
      { id: "d", text: "12" },
    ],
    correctOptionId: "a",
    explanation: "u . v = 1*3 + 2*(-1) + 0*4 = 3 - 2 + 0 = 1.",
    difficulty: "basico",
    errorType: "Produto escalar em R3",
    tags: ["vetores", "produto-escalar"],
  },
  {
    id: "q-c3-002",
    courseId: "calculo-3",
    topicId: "derivadas-parciais",
    prerequisiteIds: ["pre-funcoes", "pre-equacoes"],
    prompt: "Para f(x,y) = x^2y + y^3, qual é partial f / partial x?",
    options: [
      { id: "a", text: "2xy" },
      { id: "b", text: "x^2 + 3y^2" },
      { id: "c", text: "2xy + 3y^2" },
      { id: "d", text: "2x + y" },
    ],
    correctOptionId: "a",
    explanation: "Na derivada parcial em x, y é constante. Derive x^2y como 2xy e y^3 como 0.",
    difficulty: "medio",
    errorType: "Confusão entre variável e constante",
    tags: ["parciais", "gradiente"],
  },
  {
    id: "q-c3-003",
    courseId: "calculo-3",
    topicId: "integrais-multiplas",
    prerequisiteIds: ["pre-geometria", "pre-funcoes"],
    prompt: "A integral dupla de 1 sobre um retângulo R mede:",
    options: [
      { id: "a", text: "A área de R" },
      { id: "b", text: "O perímetro de R" },
      { id: "c", text: "Sempre 0" },
      { id: "d", text: "A diagonal de R" },
    ],
    correctOptionId: "a",
    explanation: "Integrar a função constante 1 sobre uma região plana retorna a área dessa região.",
    difficulty: "basico",
    errorType: "Interpretação geométrica da integral dupla",
    tags: ["integrais-multiplas", "area"],
  },
  {
    id: "q-c4-001",
    courseId: "calculo-4",
    topicId: "campos-vetoriais",
    prerequisiteIds: ["pre-geometria", "pre-funcoes"],
    prompt: "Para F(x,y) = (P,Q) = (x, y), a divergência em R2 é:",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "1" },
      { id: "c", text: "2" },
      { id: "d", text: "x + y" },
    ],
    correctOptionId: "c",
    explanation: "div F = partial P/partial x + partial Q/partial y = 1 + 1 = 2.",
    difficulty: "medio",
    errorType: "Definição de divergência",
    tags: ["campos-vetoriais", "divergencia"],
  },
  {
    id: "q-c4-002",
    courseId: "calculo-4",
    topicId: "integrais-linha",
    prerequisiteIds: ["pre-geometria", "pre-funcoes"],
    prompt: "Uma curva r(t) = (cos t, sen t), 0 <= t <= 2pi, descreve:",
    options: [
      { id: "a", text: "Um segmento de reta" },
      { id: "b", text: "A circunferência unitária completa" },
      { id: "c", text: "Uma parábola" },
      { id: "d", text: "Uma elipse de eixo maior 2" },
    ],
    correctOptionId: "b",
    explanation: "cos^2(t) + sen^2(t) = 1, e o intervalo percorre uma volta completa.",
    difficulty: "basico",
    errorType: "Leitura de parametrização",
    tags: ["integrais-linha", "parametrizacao"],
  },
  {
    id: "q-c4-003",
    courseId: "calculo-4",
    topicId: "teoremas-vetoriais",
    prerequisiteIds: ["pre-geometria", "pre-trigonometria"],
    prompt: "O Teorema de Green relaciona uma integral de linha fechada no plano com:",
    options: [
      { id: "a", text: "Uma integral dupla sobre a região interna" },
      { id: "b", text: "Uma integral tripla no espaco" },
      { id: "c", text: "Uma série de potências" },
      { id: "d", text: "Uma derivada ordinária" },
    ],
    correctOptionId: "a",
    explanation: "Green converte circulação na fronteira fechada em integral dupla sobre a região plana.",
    difficulty: "avancado",
    errorType: "Escolha do teorema vetorial",
    tags: ["green", "teoremas-vetoriais"],
  },
];

export function getCourse(courseId: string) {
  return courses.find((course) => course.id === courseId);
}

export function getTopic(topicId: string) {
  return topics.find((topic) => topic.id === topicId);
}

export function getPrerequisite(prerequisiteId: string) {
  return prerequisites.find((prerequisite) => prerequisite.id === prerequisiteId);
}

export function getTopicsByCourse(courseId: string) {
  return topics
    .filter((topic) => topic.courseId === courseId)
    .sort((a, b) => a.order - b.order);
}
