import type { Question, QuestionVideos, VideoKind, VideoResource } from "@/lib/types";

const playlistTitles: Record<VideoKind, string> = {
  practice: "Prática e resolução",
  theory: "Teoria e fundamentos",
  prerequisite: "Pré-requisitos para entender",
};

export const internalPlaylistUrls: Record<VideoKind, string> = {
  practice: "https://www.youtube.com/playlist?list=PLJzR3TulxvF8",
  theory: "https://www.youtube.com/playlist?list=PLYuDU_kPHyDc",
  prerequisite: "https://www.youtube.com/playlist?list=PLS24fRWWgXUc",
};

type VideoInput = Omit<
  VideoResource,
  "embedUrl" | "id" | "sourcePlaylistTitle" | "youtubeUrl"
> & {
  videoId: string;
};

function video(input: VideoInput): VideoResource {
  return {
    ...input,
    embedUrl: `https://www.youtube-nocookie.com/embed/${input.videoId}`,
    id: `${input.kind}-${input.videoId}`,
    sourcePlaylistTitle: playlistTitles[input.kind],
    sourcePlaylistUrl: internalPlaylistUrls[input.kind],
    youtubeUrl: `https://www.youtube.com/watch?v=${input.videoId}`,
  };
}

export const videoResources: VideoResource[] = [
  video({
    videoId: "-4fmIx_EZDw",
    kind: "practice",
    title: "Produtos notáveis: resumão com lista de exercícios",
    channel: "Professora Angela Matemática",
    description: "Treino direto para reconhecer quadrados perfeitos e diferença de quadrados.",
    publishedAt: "2024-03-26",
    viewCount: 106512,
    questionIds: ["q-pre-001", "q-c1-001"],
    prerequisiteIds: ["pre-produtos-notaveis", "pre-fatoracao"],
    topicIds: ["fatoracao", "limites"],
  }),
  video({
    videoId: "UECy1XbL6w8",
    kind: "theory",
    title: "Produtos notáveis: nunca mais erre",
    channel: "Dicasdemat Sandro Curió",
    description: "Revisão conceitual recente e muito vista para produtos notáveis.",
    publishedAt: "2023-10-26",
    viewCount: 1394041,
    questionIds: ["q-pre-001", "q-c1-001"],
    prerequisiteIds: ["pre-produtos-notaveis"],
    topicIds: ["fatoracao", "limites"],
  }),
  video({
    videoId: "siyovPnRTug",
    kind: "prerequisite",
    title: "Fatoração: exercícios de álgebra",
    channel: "Equaciona Com Paulo Pereira",
    description: "Lista de exercícios para consolidar fator comum, trinômios e diferença de quadrados.",
    publishedAt: "2017-12-06",
    viewCount: 62249,
    questionIds: ["q-pre-001", "q-c1-001", "q-c2-001"],
    prerequisiteIds: ["pre-fatoracao", "pre-produtos-notaveis"],
    topicIds: ["fatoracao", "limites", "tecnicas-integracao"],
  }),
  video({
    videoId: "swZRlLUMuwU",
    kind: "practice",
    title: "Função composta em 7 minutos",
    channel: "Dicasdemat Sandro Curió",
    description: "Aplicação rápida para calcular composição de funções como g(f(3)).",
    publishedAt: "2024-07-01",
    viewCount: 246016,
    questionIds: ["q-pre-002"],
    prerequisiteIds: ["pre-funcoes"],
    topicIds: ["funcoes"],
  }),
  video({
    videoId: "OqNcQoJEWNU",
    kind: "theory",
    title: "Função composta",
    channel: "Gis com Giz Matemática",
    description: "Aula conceitual para entender a ordem correta na composição.",
    publishedAt: "2022-02-02",
    viewCount: 212184,
    questionIds: ["q-pre-002"],
    prerequisiteIds: ["pre-funcoes"],
    topicIds: ["funcoes"],
  }),
  video({
    videoId: "swZRlLUMuwU",
    kind: "prerequisite",
    title: "Função composta em 7 minutos",
    channel: "Dicasdemat Sandro Curió",
    description: "Base de funções necessária antes de limites, derivadas e várias variáveis.",
    publishedAt: "2024-07-01",
    viewCount: 246016,
    questionIds: [
      "q-pre-002",
      "q-c1-002",
      "q-c1-003",
      "q-c1-004",
      "q-c2-002",
      "q-c2-003",
      "q-c2-004",
      "q-c3-002",
      "q-c3-003",
      "q-c4-001",
      "q-c4-002",
    ],
    prerequisiteIds: ["pre-funcoes"],
    topicIds: ["funcoes", "derivadas", "integrais", "funcoes-varias"],
  }),
  video({
    videoId: "DLAI0CAJn6E",
    kind: "practice",
    title: "Relação fundamental da trigonometria: demonstração e exercícios",
    channel: "Gis com Giz Matemática",
    description: "Exercícios com sen²(x) + cos²(x) = 1, base da questão de trigonometria.",
    publishedAt: "2022-11-14",
    viewCount: 360477,
    questionIds: ["q-pre-003"],
    prerequisiteIds: ["pre-trigonometria"],
    topicIds: ["trigonometria", "teoremas-vetoriais"],
  }),
  video({
    videoId: "6F7IAizrDbg",
    kind: "theory",
    title: "Identidade trigonométrica",
    channel: "Matemática no Papel",
    description: "Aula curta para reconhecer identidades trigonométricas fundamentais.",
    publishedAt: "2022-05-27",
    viewCount: 101073,
    questionIds: ["q-pre-003"],
    prerequisiteIds: ["pre-trigonometria"],
    topicIds: ["trigonometria"],
  }),
  video({
    videoId: "DLAI0CAJn6E",
    kind: "prerequisite",
    title: "Relação fundamental da trigonometria",
    channel: "Gis com Giz Matemática",
    description: "Pré-requisito para substituições, parametrizações e cálculo vetorial.",
    publishedAt: "2022-11-14",
    viewCount: 360477,
    questionIds: ["q-pre-003", "q-c4-002", "q-c4-003"],
    prerequisiteIds: ["pre-trigonometria"],
    topicIds: ["trigonometria", "integrais-linha", "teoremas-vetoriais"],
  }),
  video({
    videoId: "s3j69Fd3GWM",
    kind: "practice",
    title: "Cálculo de limites: exercícios",
    channel: "Equaciona Com Paulo Pereira",
    description: "Treino com fatoração antes de substituir no limite.",
    publishedAt: "2019-03-25",
    viewCount: 919380,
    questionIds: ["q-c1-001"],
    topicIds: ["limites"],
  }),
  video({
    videoId: "DkCHV5Kbx4o",
    kind: "theory",
    title: "Introdução e noção intuitiva de limites",
    channel: "Professor Ferretto",
    description: "Aula muito vista para entender a ideia central de limite.",
    publishedAt: "2015-03-17",
    viewCount: 4115322,
    questionIds: ["q-c1-001"],
    topicIds: ["limites"],
  }),
  video({
    videoId: "P4GQORp0g6c",
    kind: "practice",
    title: "Indeterminação nos limites",
    channel: "Professor Ferretto",
    description: "Exercícios de indeterminação que pedem manipulação algébrica antes do limite.",
    publishedAt: "2015-04-21",
    viewCount: 1167839,
    questionIds: ["q-c1-001"],
    topicIds: ["limites"],
  }),
  video({
    videoId: "91UN2cbzBGY",
    kind: "practice",
    title: "Derivada da exponencial e do logaritmo",
    channel: "Equaciona Com Paulo Pereira",
    description: "Exercícios diretamente relacionados a d/dx de e^x e ln(x).",
    publishedAt: "2019-05-31",
    viewCount: 399455,
    questionIds: ["q-c1-002"],
    topicIds: ["derivadas"],
    prerequisiteIds: ["pre-log-exp"],
  }),
  video({
    videoId: "nfARXFLUKMc",
    kind: "theory",
    title: "Derivada da função exponencial",
    channel: "Professor Ferretto",
    description: "Fundamento da derivada de e^x.",
    publishedAt: "2016-01-21",
    viewCount: 415832,
    questionIds: ["q-c1-002"],
    topicIds: ["derivadas"],
    prerequisiteIds: ["pre-log-exp"],
  }),
  video({
    videoId: "oza6zrCMOPM",
    kind: "prerequisite",
    title: "Função logarítmica: rápido e fácil",
    channel: "Dicasdemat Sandro Curió",
    description: "Pré-requisito recente para propriedades de logaritmos usadas em derivadas.",
    publishedAt: "2024-10-15",
    viewCount: 347463,
    questionIds: ["q-c1-002", "q-c2-002", "q-c2-004"],
    prerequisiteIds: ["pre-log-exp"],
    topicIds: ["log-exp", "derivadas", "integrais-improprias", "series-potencias"],
  }),
  video({
    videoId: "gMGz-dB9few",
    kind: "prerequisite",
    title: "Função exponencial: fácil e rápido",
    channel: "Dicasdemat Sandro Curió",
    description: "Pré-requisito de exponencial para derivadas, integrais e séries.",
    publishedAt: "2020-07-15",
    viewCount: 1938029,
    questionIds: ["q-c1-002", "q-c2-004"],
    prerequisiteIds: ["pre-log-exp"],
    topicIds: ["log-exp", "derivadas", "series-potencias"],
  }),
  video({
    videoId: "PMOEMs00Jz4",
    kind: "practice",
    title: "Teste da derivada primeira e segunda: máximos e mínimos",
    channel: "Equaciona Com Paulo Pereira",
    description: "Exercícios para achar pontos críticos resolvendo f'(x) = 0.",
    publishedAt: "2019-09-24",
    viewCount: 289608,
    questionIds: ["q-c1-003"],
    topicIds: ["aplicacoes-derivadas"],
  }),
  video({
    videoId: "lh0FPl4DDO0",
    kind: "theory",
    title: "Ponto crítico de uma função",
    channel: "Prof. Murakami - Matemática Rapidola",
    description: "Aula direta sobre a leitura de ponto crítico em derivadas.",
    publishedAt: "2018-06-11",
    viewCount: 105100,
    questionIds: ["q-c1-003"],
    topicIds: ["aplicacoes-derivadas"],
  }),
  video({
    videoId: "eNIxHmdAvQY",
    kind: "prerequisite",
    title: "Equação do 2º grau: aprenda com 6 exercícios",
    channel: "MARCEMÁTICA",
    description: "Base recente para resolver equações que aparecem em pontos críticos.",
    publishedAt: "2025-05-02",
    viewCount: 294989,
    questionIds: ["q-c1-003", "q-c3-002"],
    prerequisiteIds: ["pre-equacoes"],
    topicIds: ["equacoes", "aplicacoes-derivadas", "derivadas-parciais"],
  }),
  video({
    videoId: "M_xCxHcBdBo",
    kind: "practice",
    title: "Integral indefinida: se souber derivada, fica fácil",
    channel: "Equaciona Com Paulo Pereira",
    description: "Treino de primitivas e regra da potência para integrais imediatas.",
    publishedAt: "2020-02-10",
    viewCount: 939167,
    questionIds: ["q-c1-004"],
    topicIds: ["integrais"],
  }),
  video({
    videoId: "M_xCxHcBdBo",
    kind: "theory",
    title: "Integral indefinida",
    channel: "Equaciona Com Paulo Pereira",
    description: "Fundamento da ideia de primitiva como operação inversa da derivada.",
    publishedAt: "2020-02-10",
    viewCount: 939167,
    questionIds: ["q-c1-004"],
    topicIds: ["integrais"],
  }),
  video({
    videoId: "H0dGRxkodl0",
    kind: "practice",
    title: "Integração por frações parciais",
    channel: "Prof. Murakami - Matemática Rapidola",
    description: "Exercícios de decomposição por frações parciais.",
    publishedAt: "2018-07-15",
    viewCount: 217528,
    questionIds: ["q-c2-001"],
    topicIds: ["tecnicas-integracao"],
    prerequisiteIds: ["pre-fatoracao"],
  }),
  video({
    videoId: "yz-OpiPci0Y",
    kind: "theory",
    title: "Frações parciais: passo a passo",
    channel: "Matemateca - Ester Velasquez",
    description: "Fundamento organizado para começar a decomposição de fatores lineares.",
    publishedAt: "2020-11-26",
    viewCount: 112782,
    questionIds: ["q-c2-001"],
    topicIds: ["tecnicas-integracao"],
  }),
  video({
    videoId: "nCbocso-Pbw",
    kind: "practice",
    title: "Integral imprópria com limites de integração infinitos",
    channel: "Equaciona Com Paulo Pereira",
    description: "Exemplos resolvidos com integrais como ∫ 1/x².",
    publishedAt: "2020-04-06",
    viewCount: 214519,
    questionIds: ["q-c2-002"],
    topicIds: ["integrais-improprias"],
  }),
  video({
    videoId: "O6pv0UsZ5ys",
    kind: "theory",
    title: "Integral imprópria",
    channel: "Prof. Murakami - Matemática Rapidola",
    description: "Base conceitual para escrever a integral imprópria como limite.",
    publishedAt: "2019-09-21",
    viewCount: 80356,
    questionIds: ["q-c2-002"],
    topicIds: ["integrais-improprias"],
  }),
  video({
    videoId: "7WgL16ehNuU",
    kind: "practice",
    title: "Como calcular o limite de sequências",
    channel: "Matemateca - Ester Velasquez",
    description: "Exercícios de limites de sequências como a_n = 1/n.",
    publishedAt: "2022-12-12",
    viewCount: 119850,
    questionIds: ["q-c2-003"],
    topicIds: ["sequencias-series"],
  }),
  video({
    videoId: "7WgL16ehNuU",
    kind: "theory",
    title: "Limite de sequências",
    channel: "Matemateca - Ester Velasquez",
    description: "Fundamento para entender convergência de sequências numéricas.",
    publishedAt: "2022-12-12",
    viewCount: 119850,
    questionIds: ["q-c2-003"],
    topicIds: ["sequencias-series"],
  }),
  video({
    videoId: "SkwQIg5oIKw",
    kind: "practice",
    title: "Séries de Taylor e Maclaurin: definição e exercícios",
    channel: "Matemateca - Ester Velasquez",
    description: "Exercícios para reconhecer os primeiros termos de séries de Taylor.",
    publishedAt: "2023-04-27",
    viewCount: 72785,
    questionIds: ["q-c2-004"],
    topicIds: ["series-potencias"],
  }),
  video({
    videoId: "IwKd7P1ckLI",
    kind: "theory",
    title: "Série de Taylor e Maclaurin",
    channel: "Equaciona Com Paulo Pereira",
    description: "Aula muito vista sobre a expansão de funções como e^x.",
    publishedAt: "2019-10-21",
    viewCount: 257381,
    questionIds: ["q-c2-004"],
    topicIds: ["series-potencias"],
  }),
  video({
    videoId: "vI3HTBycd2Y",
    kind: "practice",
    title: "Produto escalar, norma e ângulo entre vetores",
    channel: "Bote Fé na Matemática",
    description: "Exercícios diretamente ligados ao cálculo de produto escalar.",
    publishedAt: "2021-05-14",
    viewCount: 13452,
    questionIds: ["q-c3-001"],
    topicIds: ["vetores"],
    prerequisiteIds: ["pre-geometria"],
  }),
  video({
    videoId: "eAAKzZcbITI",
    kind: "theory",
    title: "Mega aula completa de vetores",
    channel: "Professor Boaro",
    description: "Aula ampla e muito vista para revisar vetores antes de cálculo vetorial.",
    publishedAt: "2019-08-04",
    viewCount: 1331741,
    questionIds: ["q-c3-001", "q-c4-001", "q-c4-002", "q-c4-003"],
    prerequisiteIds: ["pre-geometria"],
    topicIds: ["vetores", "campos-vetoriais", "integrais-linha", "teoremas-vetoriais"],
  }),
  video({
    videoId: "xeqom87mlY4",
    kind: "prerequisite",
    title: "Geometria analítica com questões",
    channel: "Praticando Matemática com Maicon Meneguci",
    description: "Pré-requisito de geometria analítica para vetores, regiões e campos.",
    publishedAt: "2021-07-26",
    viewCount: 134300,
    questionIds: ["q-c3-001", "q-c3-003", "q-c4-001", "q-c4-002", "q-c4-003"],
    prerequisiteIds: ["pre-geometria"],
    topicIds: ["geometria-analitica", "vetores", "integrais-multiplas"],
  }),
  video({
    videoId: "fa_FJvqxSeA",
    kind: "practice",
    title: "Derivadas parciais: exercícios resolvidos",
    channel: "Prof Raimundo Augusto",
    description: "Exercícios curtos para diferenciar tratando uma variável como constante.",
    publishedAt: "2020-06-26",
    viewCount: 28711,
    questionIds: ["q-c3-002"],
    topicIds: ["derivadas-parciais"],
  }),
  video({
    videoId: "2fjlR8ST_vs",
    kind: "theory",
    title: "Introdução às derivadas parciais",
    channel: "Prof. Murakami - Matemática Rapidola",
    description: "Aula completa e muito vista para o fundamento de derivadas parciais.",
    publishedAt: "2020-09-30",
    viewCount: 246454,
    questionIds: ["q-c3-002"],
    topicIds: ["derivadas-parciais"],
  }),
  video({
    videoId: "Z9ORGP7YLLE",
    kind: "practice",
    title: "Integral dupla: exercício fácil",
    channel: "Somatize - Profª Edna - Matemática",
    description: "Exercício prático para interpretar integral dupla como área.",
    publishedAt: "2017-06-16",
    viewCount: 139558,
    questionIds: ["q-c3-003"],
    topicIds: ["integrais-multiplas"],
  }),
  video({
    videoId: "YWS21b1pbkM",
    kind: "theory",
    title: "Integral dupla: regiões retangulares",
    channel: "Prof. Murakami - Matemática Rapidola",
    description: "Aula direta sobre integrais duplas em regiões retangulares.",
    publishedAt: "2018-12-03",
    viewCount: 220037,
    questionIds: ["q-c3-003"],
    topicIds: ["integrais-multiplas"],
  }),
  video({
    videoId: "jEv90om82IY",
    kind: "practice",
    title: "Divergente de um campo vetorial",
    channel: "Prof. Murakami - Matemática Rapidola",
    description: "Exercício direto de divergente para campos F = (P, Q).",
    publishedAt: "2019-05-27",
    viewCount: 28998,
    questionIds: ["q-c4-001"],
    topicIds: ["campos-vetoriais"],
  }),
  video({
    videoId: "jEv90om82IY",
    kind: "theory",
    title: "Divergente de um campo vetorial",
    channel: "Prof. Murakami - Matemática Rapidola",
    description: "Fundamento para calcular ∂P/∂x + ∂Q/∂y.",
    publishedAt: "2019-05-27",
    viewCount: 28998,
    questionIds: ["q-c4-001"],
    topicIds: ["campos-vetoriais"],
  }),
  video({
    videoId: "zwjR1StdNjY",
    kind: "practice",
    title: "Parametrização de uma circunferência",
    channel: "Prof. Murakami - Matemática Rapidola",
    description: "Exercício alinhado à curva r(t) = (cos t, sen t).",
    publishedAt: "2020-03-16",
    viewCount: 51846,
    questionIds: ["q-c4-002"],
    topicIds: ["integrais-linha"],
  }),
  video({
    videoId: "-1R_bh85RLQ",
    kind: "theory",
    title: "Curvas parametrizadas: reta, circunferência e elipse",
    channel: "Matemateca - Ester Velasquez",
    description: "Fundamento visual para reconhecer circunferências parametrizadas.",
    publishedAt: "2022-01-31",
    viewCount: 60981,
    questionIds: ["q-c4-002"],
    topicIds: ["integrais-linha"],
  }),
  video({
    videoId: "jQ-SHqRhDbs",
    kind: "practice",
    title: "Exercício resolvido: Teorema de Green",
    channel: "Matemateca - Ester Velasquez",
    description: "Exercício recente e específico sobre a conversão proposta pelo Teorema de Green.",
    publishedAt: "2024-08-05",
    viewCount: 7570,
    questionIds: ["q-c4-003"],
    topicIds: ["teoremas-vetoriais"],
  }),
  video({
    videoId: "M0F-XY51Kx8",
    kind: "theory",
    title: "O que é o Teorema de Green e como utilizar",
    channel: "Matemateca - Ester Velasquez",
    description: "Aula atual para entender quando Green troca integral de linha por integral dupla.",
    publishedAt: "2023-08-10",
    viewCount: 38561,
    questionIds: ["q-c4-003"],
    topicIds: ["teoremas-vetoriais"],
  }),
  video({
    videoId: "af6Tq3OVWxI",
    kind: "theory",
    title: "Teorema de Green",
    channel: "Prof. Murakami - Matemática Rapidola",
    description: "Aula mais vista entre os candidatos sobre o Teorema de Green.",
    publishedAt: "2020-06-10",
    viewCount: 91456,
    questionIds: ["q-c4-003"],
    topicIds: ["teoremas-vetoriais"],
  }),
];

export function getVideosForQuestion(question: Question): QuestionVideos {
  return {
    practice: getMatches(question, "practice"),
    theory: getMatches(question, "theory"),
    prerequisite: getMatches(question, "prerequisite"),
  };
}

function getMatches(question: Question, kind: VideoKind) {
  const directMatches = videoResources.filter(
    (resource) =>
      resource.kind === kind && resource.questionIds?.includes(question.id),
  );

  const matches = directMatches.length
    ? directMatches
    : videoResources.filter((resource) => {
    if (resource.kind !== kind) {
      return false;
    }

    return (
      resource.topicIds?.includes(question.topicId) ||
      resource.prerequisiteIds?.some((id) => question.prerequisiteIds.includes(id))
    );
  });

  return matches
    .sort((left, right) => (right.viewCount ?? 0) - (left.viewCount ?? 0))
    .slice(0, 3);
}
